# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build (Fix All Runtime Issues)
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_SCHEME: 'modamaskavo'

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Fix React Native Runtime modules for iOS 11
        script: |
          # 1. Criar React-RuntimeApple vazio
          mkdir -p node_modules/react-native/ReactCommon/react/runtime/platform/ios
          cat > node_modules/react-native/ReactCommon/react/runtime/platform/ios/React-RuntimeApple.podspec << 'EOF'
          Pod::Spec.new do |s|
            s.name                   = "React-RuntimeApple"
            s.version                = "1000.0.0"
            s.summary                = "Dummy podspec for iOS 11 compatibility"
            s.homepage               = "https://reactnative.dev/"
            s.license                = "MIT"
            s.author                 = "Meta Platforms, Inc. and its affiliates"
            s.platforms              = { :ios => "11.0" }
            s.source                 = { :path => "." }
            s.source_files           = "**/*.{h,m,mm,cpp,c}"
            s.header_dir             = "React"
          end
          EOF
          touch node_modules/react-native/ReactCommon/react/runtime/platform/ios/dummy.cpp

          # 2. Modificar React-RCTRuntime para iOS 11
          if [ -f "node_modules/react-native/React/Runtime/React-RCTRuntime.podspec" ]; then
            sed -i '' 's/s.platforms.*= { :ios => "[0-9.]*" }/s.platforms = { :ios => "11.0" }/g' node_modules/react-native/React/Runtime/React-RCTRuntime.podspec
          fi

          # 3. Criar arquivo dummy se não existir
          mkdir -p node_modules/react-native/React/Runtime
          touch node_modules/react-native/React/Runtime/dummy.cpp

          # 4. Verificar se os arquivos foram criados
          echo "Verificando arquivos criados:"
          ls -la node_modules/react-native/ReactCommon/react/runtime/platform/ios/ || echo "Diretório RuntimeApple não encontrado"
          ls -la node_modules/react-native/React/Runtime/ || echo "Diretório RCTRuntime não encontrado"

      - name: Setup environment
        script: |
          cd ios
          cat > .xcode.env << EOF
          export NODE_BINARY=node
          export RCT_NEW_ARCH_ENABLED=0
          export HERMES_ENABLED=0
          EOF

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install --verbose

      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -workspace modamaskavo.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO \
            VALID_ARCHS=arm64 \
            IPHONEOS_DEPLOYMENT_TARGET=11.0 \
            build

    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - ios/build/Build/Products/Release-iphoneos/*.app
