# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_SCHEME: 'modamaskavo'

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          # Limpeza completa
          pod deintegrate || true
          rm -rf Pods
          rm -f Podfile.lock
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ~/.cocoapods/repos/trunk
          
          # Instalar pods
          pod install --verbose

      - name: Build iOS app
        script: |
          cd ios
          if [ -d "modamaskavo.xcworkspace" ]; then
            echo "Usando .xcworkspace"
            xcodebuild -workspace modamaskavo.xcworkspace \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -destination generic/platform=iOS \
              -sdk iphoneos \
              CODE_SIGNING_ALLOWED=NO \
              CODE_SIGNING_REQUIRED=NO \
              ONLY_ACTIVE_ARCH=NO \
              VALID_ARCHS=arm64 \
              GCC_TREAT_WARNINGS_AS_ERRORS=NO \
              CLANG_WARN_DOCUMENTATION_COMMENTS=NO \
              clean build
          else
            echo "Usando .xcodeproj"
            xcodebuild -project modamaskavo.xcodeproj \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -destination generic/platform=iOS \
              -sdk iphoneos \
              CODE_SIGNING_ALLOWED=NO \
              CODE_SIGNING_REQUIRED=NO \
              ONLY_ACTIVE_ARCH=NO \
              VALID_ARCHS=arm64 \
              GCC_TREAT_WARNINGS_AS_ERRORS=NO \
              CLANG_WARN_DOCUMENTATION_COMMENTS=NO \
              clean build
          fi

    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - ios/build/Build/Products/Release-iphoneos/*.app
