# codemagic.yaml
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Fix React Runtime Issues
        script: |
          # Criar diret처rio React-RuntimeApple se n찾o existir
          mkdir -p node_modules/react-native/ReactCommon/react/runtime/platform/ios
          
          # Criar podspec vazio para React-RuntimeApple
          cat > node_modules/react-native/ReactCommon/react/runtime/platform/ios/React-RuntimeApple.podspec << 'EOF'
          Pod::Spec.new do |s|
            s.name                   = "React-RuntimeApple"
            s.version                = "1000.0.0"
            s.summary                = "Dummy podspec for compatibility"
            s.homepage               = "https://reactnative.dev/"
            s.license                = "MIT"
            s.author                 = "Meta Platforms, Inc."
            s.platforms              = { :ios => "13.0" }
            s.source                 = { :path => "." }
            s.source_files           = "**/*.{h,m,mm,cpp,c}"
            s.header_dir             = "React"
          end
          EOF
          
          # Criar diret처rio React-RCTRuntime se n찾o existir
          mkdir -p node_modules/react-native/React/Runtime
          
          # Criar podspec vazio para React-RCTRuntime
          cat > node_modules/react-native/React/Runtime/React-RCTRuntime.podspec << 'EOF'
          Pod::Spec.new do |s|
            s.name                   = "React-RCTRuntime"
            s.version                = "1000.0.0"
            s.summary                = "Dummy podspec for compatibility"
            s.homepage               = "https://reactnative.dev/"
            s.license                = "MIT"
            s.author                 = "Meta Platforms, Inc."
            s.platforms              = { :ios => "13.0" }
            s.source                 = { :path => "." }
            s.source_files           = "**/*.{h,m,mm,cpp,c}"
            s.header_dir             = "React"
          end
          EOF
          
          # Criar arquivos fonte vazios
          touch node_modules/react-native/ReactCommon/react/runtime/platform/ios/dummy.cpp
          touch node_modules/react-native/React/Runtime/dummy.cpp
          
      - name: Clean CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
