# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build Universal
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_SCHEME: 'modamaskavo'

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Patch React Native pods script
        script: |
          # Fazer backup
          cp node_modules/react-native/scripts/react_native_pods.rb node_modules/react-native/scripts/react_native_pods.rb.backup
          
          # Remover todas as linhas que incluem Runtime
          sed -i '' '/React-RuntimeApple/d' node_modules/react-native/scripts/react_native_pods.rb
          sed -i '' '/React-RCTRuntime/d' node_modules/react-native/scripts/react_native_pods.rb
          sed -i '' '/RuntimeApple/d' node_modules/react-native/scripts/react_native_pods.rb
          sed -i '' '/RCTRuntime/d' node_modules/react-native/scripts/react_native_pods.rb
          
          # Verificar o que foi removido
          echo "Verificando se Runtime foi removido:"
          grep -n "Runtime" node_modules/react-native/scripts/react_native_pods.rb || echo "Runtime removido com sucesso"

      - name: Setup environment
        script: |
          cd ios
          cat > .xcode.env << EOF
          export NODE_BINARY=node
          EOF

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install --verbose

      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -workspace modamaskavo.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build

    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - ios/build/Build/Products/Release-iphoneos/*.app
