# codemagic.yaml
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Remove React Runtime Apple
        script: |
          # Remover diretório React-RuntimeApple
          rm -rf node_modules/react-native/ReactCommon/react/runtime/platform/ios
          
          # Modificar react_native_pods.rb para não incluir RuntimeApple
          sed -i '' '/React-RuntimeApple/d' node_modules/react-native/scripts/react_native_pods.rb
          
          # Verificar se foi removido
          echo "Verificando se Runtime foi removido:"
          grep -n "RuntimeApple" node_modules/react-native/scripts/react_native_pods.rb || echo "RuntimeApple removido com sucesso"
          
      - name: Clean CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
