# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: codemagic

    environment:
      groups:
        - apple_developer_portal_credentials
      vars:
        XCODE_SCHEME: 'modamaskavo'
      ios_signing:
        distribution_type: ad_hoc  # ← Mudança aqui
        bundle_identifier: com.modamaskavo

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods
          rm -f Podfile.lock
          pod install

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          if [ -d "ios/modamaskavo.xcworkspace" ]; then
            echo "Usando .xcworkspace"
            xcode-project build-ipa \
              --workspace "ios/modamaskavo.xcworkspace" \
              --scheme "$XCODE_SCHEME" \
              --clean
          elif [ -d "ios/modamaskavo.xcodeproj" ]; then
            echo "Usando .xcodeproj"
            xcode-project build-ipa \
              --project "ios/modamaskavo.xcodeproj" \
              --scheme "$XCODE_SCHEME" \
              --clean
          else
            echo "Erro: Não foi encontrado .xcworkspace nem .xcodeproj na pasta ios/"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    # Removendo publishing temporariamente para testar o build
    # publishing:
    #   app_store_connect:
    #     auth: integration
    #     submit_to_testflight: true
    #     submit_to_app_store: false
