# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build (RN 0.68 - iOS 11 Compatible)
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_SCHEME: 'modamaskavo'

    scripts:
      - name: Downgrade React Native to 0.68.x
        script: |
          # Fazer backup do package.json atual
          cp package.json package.json.backup
          
          # Instalar React Native 0.68.7 (última versão que suporta iOS 11)
          npm install react-native@0.68.7 --save
          npm install react@18.1.0 --save
          
          # Instalar dependências
          npm install

      - name: Setup environment
        script: |
          cd ios
          cat > .xcode.env << EOF
          export NODE_BINARY=node
          export RCT_NEW_ARCH_ENABLED=0
          export HERMES_ENABLED=0
          EOF

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install --verbose

      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -workspace modamaskavo.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO \
            VALID_ARCHS=arm64 \
            IPHONEOS_DEPLOYMENT_TARGET=11.0 \
            build

    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - ios/build/Build/Products/Release-iphoneos/*.app
