workflows:
  ios-workflow:
    name: iOS Build Definitivo
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          
      - name: Create minimal Podfile
        script: |
          cat > ios/Podfile << 'EOF'
          platform :ios, '13.0'
          
          target 'modamaskavo' do
            # Apenas o essencial
            pod 'React', :path => '../node_modules/react-native', :subspecs => [
              'Core',
              'CxxBridge',
              'DevSupport',
              'RCTActionSheet',
              'RCTAnimation',
              'RCTBlob',
              'RCTImage',
              'RCTLinking',
              'RCTNetwork',
              'RCTSettings',
              'RCTText',
              'RCTVibration',
              'RCTWebSocket',
            ]
            
            # Yoga
            pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
            
            # Third party
            pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
            pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
            
            # Suas libs
            pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
            pod 'react-native-webview', :path => '../node_modules/react-native-webview'
            
            post_install do |installer|
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                end
              end
            end
          end
          EOF
          
      - name: Pod install
        script: |
          cd ios && pod install
          
      - name: Build
        script: |
          cd ios
          xcodebuild -workspace modamaskavo.xcworkspace -scheme modamaskavo -configuration Release -destination generic/platform=iOS archive -archivePath build/app.xcarchive
          
    artifacts:
      - ios/build/*.xcarchive
