# codemagic.yaml - VERSÃO CORRIGIDA COM ARTIFACTS
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
          
      - name: HACK BRUTAL - Corrigir fast_float.podspec
        script: |
          # Corrigir fast_float.podspec para usar iOS 12.0
          mkdir -p node_modules/react-native/third-party-podspecs
          cat > node_modules/react-native/third-party-podspecs/fast_float.podspec << 'EOF'
          Pod::Spec.new do |s|
            s.name                   = "fast_float"
            s.version                = "3.4.0"
            s.summary                = "Fast and exact implementation of the C++ from_chars functions for float and double types"
            s.homepage               = "https://github.com/fastfloat/fast_float"
            s.license                = "MIT"
            s.author                 = { "Daniel Lemire" => "lemire@gmail.com" }
            s.platforms              = { :ios => "12.0", :osx => "10.15" }
            s.source                 = { :git => "https://github.com/fastfloat/fast_float.git", :tag => "v3.4.0" }
            s.source_files           = "include/**/*.h"
            s.header_dir             = "fast_float"
            s.public_header_files    = "include/**/*.h"
            s.header_mappings_dir    = "include"
            s.requires_arc           = false
            s.pod_target_xcconfig    = {
              'IPHONEOS_DEPLOYMENT_TARGET' => '12.0',
              'MACOSX_DEPLOYMENT_TARGET' => '10.15',
              'USE_HEADERMAP' => 'NO',
              'CLANG_CXX_LANGUAGE_STANDARD' => 'c++14',
              'CLANG_CXX_LIBRARY' => 'libc++'
            }
          end
          EOF
          
          echo "✅ fast_float.podspec corrigido para iOS 12.0!"
          
      - name: HACK BRUTAL - Corrigir fmt.podspec
        script: |
          # Corrigir fmt.podspec - SEM :file na licença
          cat > node_modules/react-native/third-party-podspecs/fmt.podspec << 'EOF'
          Pod::Spec.new do |s|
            s.name                   = "fmt"
            s.version                = "6.2.1"
            s.summary                = "A modern formatting library"
            s.homepage               = "https://github.com/fmtlib/fmt"
            s.license                = "MIT"
            s.author                 = { "Victor Zverovich" => "victor.zverovich@gmail.com" }
            s.platforms              = { :ios => "12.0", :osx => "10.15" }
            s.source                 = { :git => "https://github.com/fmtlib/fmt.git", :tag => "6.2.1" }
            s.source_files           = "include/**/*.h", "src/*.cc"
            s.header_dir             = "fmt"
            s.public_header_files    = "include/**/*.h"
            s.header_mappings_dir    = "include"
            s.requires_arc           = false
            s.pod_target_xcconfig    = {
              'IPHONEOS_DEPLOYMENT_TARGET' => '12.0',
              'MACOSX_DEPLOYMENT_TARGET' => '10.15',
              'USE_HEADERMAP' => 'NO',
              'CLANG_CXX_LANGUAGE_STANDARD' => 'c++14',
              'CLANG_CXX_LIBRARY' => 'libc++'
            }
          end
          EOF
          
          echo "✅ fmt.podspec corrigido!"
          
      - name: Create Podfile with iOS 12.0 ULTRA FORÇADO
        script: |
          cat > ios/Podfile << 'EOF'
          require_relative '../node_modules/react-native/scripts/react_native_pods'
          
          platform :ios, '12.0'
          
          target 'modamaskavo' do
            config = use_native_modules!
            
            use_react_native!(
              :path => config[:reactNativePath],
              :hermes_enabled => false,
              :fabric_enabled => false,
              :new_arch_enabled => false
            )
            
            post_install do |installer|
              react_native_post_install(installer)
              
              # Forçar iOS 12.0 em TODOS os pods
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                  config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.15'
                  config.build_settings['RCT_NEW_ARCH_ENABLED'] = 'NO'
                  config.build_settings['ENABLE_BITCODE'] = 'NO'
                  config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
                  config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
                  config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
                end
              end
            end
          end
          EOF
          
          echo "✅ Podfile criado com iOS 12.0 ULTRA FORÇADO!"
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update --verbose
          
      - name: Verificar arquivos gerados
        script: |
          cd ios
          echo "=== Verificando arquivos no diretório ios ==="
          ls -la
          
          # Verificar se workspace existe
          if [ -d "modamaskavo.xcworkspace" ]; then
            echo "✅ Workspace encontrado!"
          else
            echo "❌ Workspace não encontrado. Listando arquivos .xcworkspace:"
            find . -name "*.xcworkspace" -type d
          fi
          
          # Verificar se projeto existe
          if [ -d "modamaskavo.xcodeproj" ]; then
            echo "✅ Projeto encontrado!"
          else
            echo "❌ Projeto não encontrado. Listando arquivos .xcodeproj:"
            find . -name "*.xcodeproj" -type d
          fi
          
      - name: Criar exportOptions.plist
        script: |
          cd ios
          cat > exportOptions.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>compileBitcode</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF
          
          echo "✅ exportOptions.plist criado!"
          
      - name: Build and Archive iOS app COM WORKSPACE
        script: |
          cd ios
          
          # Criar diretório de build
          mkdir -p build
          
          echo "=== Iniciando build do iOS com WORKSPACE ==="
          
          # Build e Archive usando WORKSPACE (correto após CocoaPods)
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build/modamaskavo.xcarchive \
                     archive
          
          echo "=== Archive concluído, iniciando export ==="
          
          # Exportar IPA
          xcodebuild -exportArchive \
                     -archivePath build/modamaskavo.xcarchive \
                     -exportPath build \
                     -exportOptionsPlist exportOptions.plist
          
          echo "=== Export concluído ==="
          
          # Listar arquivos gerados
          echo "=== Arquivos gerados ==="
          find build -name "*.ipa" -o -name "*.app" -o -name "*.xcarchive" | head -10
          
          # Verificar se IPA foi criado
          if find build -name "*.ipa" | grep -q .; then
            echo "✅ IPA criado com sucesso!"
            find build -name "*.ipa" -exec ls -la {} \;
          else
            echo "❌ IPA não foi criado"
            echo "Conteúdo do diretório build:"
            ls -la build/
            echo "Conteúdo completo:"
            find build -type f | head -20
          fi
          
    # SEÇÃO DE ARTEFATOS - CRÍTICA PARA DOWNLOAD
    artifacts:
      # Arquivo IPA principal (mais importante)
      - ios/build/*.ipa
      - ios/build/**/*.ipa
      
      # Archive do Xcode
      - ios/build/*.xcarchive
      - ios/build/**/*.xcarchive
      
      # App bundle
      - ios/build/*.app
      - ios/build/**/*.app
      
      # Símbolos de debug
      - ios/build/**/*.dSYM
      - ios/build/**/*.dSYM.zip
      
      # Logs importantes
      - ios/build/logs/**
      - "**/*.log"
      - "**/*.crash"
      
      # Relatórios de build
      - ios/build/reports/**
      - ios/DerivedData/*/Logs/**
      
      # Arquivos de configuração
      - ios/exportOptions.plist
      - ios/Podfile
      - ios/Podfile.lock
      
    # PUBLICAÇÃO POR EMAIL
    publishing:
      email:
        recipients:
          - alissonschmitz2@hotmail.com
        notify:
          success: true
          failure: true
