# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_SCHEME: 'modamaskavo'
        RCT_NEW_ARCH_ENABLED: 0
        RCT_FABRIC_ENABLED: 0

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Setup React Native environment
        script: |
          cd ios
          cat > .xcode.env << EOF
          export NODE_BINARY=node
          export RCT_NEW_ARCH_ENABLED=0
          export RCT_FABRIC_ENABLED=0
          export RCT_TURBO_MODULE_ENABLED=0
          EOF

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods
          rm -f Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData
          pod install --verbose

      - name: Build iOS app (Simulator)
        script: |
          cd ios
          xcodebuild -workspace modamaskavo.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination generic/platform=iOS\ Simulator \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO \
            GCC_TREAT_WARNINGS_AS_ERRORS=NO \
            build

    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
