# codemagic.yaml - SOLUÇÃO BRUTAL E DEFINITIVA
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: HACK BRUTAL - Criar script que cria podspecs sob demanda
        script: |
          # Criar script que intercepta erros de podspec
          cat > fix_podspecs.rb << 'EOF'
          require 'fileutils'

          def create_podspec(name, path)
            FileUtils.mkdir_p(path)
            File.write("#{path}/#{name}.podspec", <<~PODSPEC)
              Pod::Spec.new do |s|
                s.name                   = "#{name}"
                s.version                = "1000.0.0"
                s.summary                = "Auto-generated podspec for compatibility"
                s.homepage               = "https://reactnative.dev/"
                s.license                = "MIT"
                s.author                 = "Meta Platforms, Inc."
                s.platforms              = { :ios => "15.0" }
                s.source                 = { :path => "." }
                s.source_files           = "*.{h,m,mm,cpp,c}"
                s.header_dir             = "React"
                s.public_header_files    = "*.h"
              end
            PODSPEC
            FileUtils.touch("#{path}/dummy.cpp")
            puts "✅ Created #{name}.podspec"
          end

          # Lista de todos os podspecs problemáticos conhecidos
          podspecs = [
            ["React-RuntimeApple", "node_modules/react-native/ReactCommon/react/runtime/platform/ios"],
            ["React-RuntimeCore", "node_modules/react-native/ReactCommon/react/runtime"],
            ["React-logger", "node_modules/react-native/ReactCommon/logger"],
            ["React-oscompat", "node_modules/react-native/ReactCommon/oscompat"],
            ["React-NativeModulesApple", "node_modules/react-native/ReactCommon/react/nativemodule/core/platform/ios"],
            ["React-RCTNetwork", "node_modules/react-native/Libraries/Network"],
            ["FBLazyVector", "node_modules/react-native/Libraries/FBLazyVector"],
            ["React-Core", "node_modules/react-native/React"],
            ["React-CoreModules", "node_modules/react-native/React/CoreModules"],
            ["React-RCTAppDelegate", "node_modules/react-native/Libraries/AppDelegate"],
            ["React-RCTImage", "node_modules/react-native/Libraries/Image"],
            ["React-RCTText", "node_modules/react-native/Libraries/Text"],
            ["React-RCTVibration", "node_modules/react-native/Libraries/Vibration"],
            ["React-RCTLinking", "node_modules/react-native/Libraries/LinkingIOS"],
            ["React-RCTSettings", "node_modules/react-native/Libraries/Settings"],
            ["React-RCTBlob", "node_modules/react-native/Libraries/Blob"],
            ["React-RCTAnimation", "node_modules/react-native/Libraries/NativeAnimation"],
            ["React-jsi", "node_modules/react-native/ReactCommon/jsi"],
            ["React-jsiexecutor", "node_modules/react-native/ReactCommon/jsiexecutor"],
            ["React-jsinspector", "node_modules/react-native/ReactCommon/jsinspector"],
            ["React-callinvoker", "node_modules/react-native/ReactCommon/callinvoker"],
            ["React-runtimeexecutor", "node_modules/react-native/ReactCommon/runtimeexecutor"],
            ["React-perflogger", "node_modules/react-native/ReactCommon/reactperflogger"],
            ["React-cxxreact", "node_modules/react-native/ReactCommon/cxxreact"],
            ["React-hermes", "node_modules/react-native/ReactCommon/hermes"],
            ["React-utils", "node_modules/react-native/ReactCommon/react/utils"],
            ["React-debug", "node_modules/react-native/ReactCommon/react/debug"],
            ["React-Mapbuffer", "node_modules/react-native/ReactCommon/react/renderer/mapbuffer"],
            ["Yoga", "node_modules/react-native/ReactCommon/yoga"],
            ["ReactCommon", "node_modules/react-native/ReactCommon"]
          ]

          podspecs.each do |name, path|
            create_podspec(name, path)
          end

          puts "✅ Todos os podspecs criados!"
          EOF
          
          # Executar o script Ruby
          ruby fix_podspecs.rb
          
      - name: Forçar iOS 15.0 em todos os podspecs existentes
        script: |
          # Modificar todos os podspecs existentes
          find node_modules -name "*.podspec" -type f | while read podspec; do
            echo "Modificando $podspec"
            # Usar perl para modificação mais robusta
            perl -i -pe 's/s\.platforms.*=.*\{.*:ios.*=>.*/s.platforms = { :ios => "15.0" }/' "$podspec"
            perl -i -pe 's/ios\.deployment_target.*=.*/ios.deployment_target = "15.0"/' "$podspec"
            perl -i -pe 's/spec\.ios\.deployment_target.*=.*/spec.ios.deployment_target = "15.0"/' "$podspec"
          done
          
          echo "✅ Todos os podspecs modificados!"
          
      - name: Create Podfile with iOS 15.0
        script: |
          cat > ios/Podfile << 'EOF'
          require_relative '../node_modules/react-native/scripts/react_native_pods'
          
          platform :ios, '15.0'
          
          target 'modamaskavo' do
            config = use_native_modules!
            
            use_react_native!(
              :path => config[:reactNativePath],
              :hermes_enabled => false,
              :fabric_enabled => false,
              :new_arch_enabled => false
            )
            
            post_install do |installer|
              react_native_post_install(installer)
              
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
                  config.build_settings['RCT_NEW_ARCH_ENABLED'] = 'NO'
                end
              end
            end
          end
          EOF
      - name: Clean everything
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          rm -rf build
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
