# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build (Manual Exclusion)
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_SCHEME: 'modamaskavo'

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Setup environment
        script: |
          cd ios
          cat > .xcode.env << EOF
          export NODE_BINARY=node
          export RCT_NEW_ARCH_ENABLED=0
          export HERMES_ENABLED=0
          EOF

      - name: Modify React Native to exclude RuntimeApple
        script: |
          cd node_modules/react-native/ReactCommon/react/runtime/platform/ios
          # Renomear ou remover o podspec problemático
          if [ -f "React-RuntimeApple.podspec" ]; then
            mv React-RuntimeApple.podspec React-RuntimeApple.podspec.bak
          fi

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install --verbose

      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -workspace modamaskavo.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO \
            VALID_ARCHS=arm64 \
            IPHONEOS_DEPLOYMENT_TARGET=11.0 \
            build

    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - ios/build/Build/Products/Release-iphoneos/*.app
