# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_SCHEME: 'modamaskavo'

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods
          rm -f Podfile.lock
          pod install

      - name: Build iOS app (without signing)
        script: |
          if [ -d "ios/modamaskavo.xcworkspace" ]; then
            xcodebuild -workspace "ios/modamaskavo.xcworkspace" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -destination generic/platform=iOS \
              CODE_SIGNING_ALLOWED=NO \
              CODE_SIGNING_REQUIRED=NO \
              build
          else
            xcodebuild -project "ios/modamaskavo.xcodeproj" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -destination generic/platform=iOS \
              CODE_SIGNING_ALLOWED=NO \
              CODE_SIGNING_REQUIRED=NO \
              build
          fi

    artifacts:
      - /tmp/xcodebuild_logs/*.log
