# codemagic.yaml - CRIANDO O PODSPEC FALTANTE
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Create RuntimeApple podspec
        script: |
          # Criar o diretório que o CocoaPods está procurando
          mkdir -p node_modules/react-native/ReactCommon/react/runtime/platform/ios
          
          # Criar o podspec que está faltando
          cat > node_modules/react-native/ReactCommon/react/runtime/platform/ios/React-RuntimeApple.podspec << 'EOF'
          Pod::Spec.new do |s|
            s.name                   = "React-RuntimeApple"
            s.version                = "1000.0.0"
            s.summary                = "Empty podspec for compatibility"
            s.homepage               = "https://reactnative.dev/"
            s.license                = "MIT"
            s.author                 = "Meta Platforms, Inc."
            s.platforms              = { :ios => "15.0" }
            s.source                 = { :path => "." }
            s.source_files           = "*.{h,m,mm,cpp,c}"
            s.header_dir             = "React"
            
            # Dependências mínimas
            s.dependency "React-Core"
            s.dependency "React-jsi"
          end
          EOF
          
          # Criar arquivo fonte dummy
          touch node_modules/react-native/ReactCommon/react/runtime/platform/ios/dummy.cpp
          
          echo "✅ RuntimeApple podspec criado!"
          
      - name: Force disable New Architecture
        script: |
          echo "export RCT_NEW_ARCH_ENABLED=0" > ios/.xcode.env
          echo "export NODE_BINARY=node" >> ios/.xcode.env
          
      - name: Create correct Podfile
        script: |
          cat > ios/Podfile << 'EOF'
          require_relative '../node_modules/react-native/scripts/react_native_pods'
          
          platform :ios, '15.0'
          
          target 'modamaskavo' do
            config = use_native_modules!
            
            use_react_native!(
              :path => config[:reactNativePath],
              :hermes_enabled => false,
              :fabric_enabled => false,
              :new_arch_enabled => false
            )
            
            post_install do |installer|
              react_native_post_install(installer)
              
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
                  config.build_settings['RCT_NEW_ARCH_ENABLED'] = 'NO'
                end
              end
            end
          end
          EOF
      - name: Clean everything
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          rm -rf build
      - name: Install CocoaPods dependencies
        script: |
          cd ios && RCT_NEW_ARCH_ENABLED=0 pod install
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
