workflows:
  ios-workflow-react-native:
    name: iOS Build com React Native
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: |
          echo "📦 Instalando dependências npm..."
          npm install
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          
          echo "📦 Instalando CocoaPods..."
          
          # Instalar CocoaPods se não estiver instalado
          if ! command -v pod &> /dev/null; then
            echo "Instalando CocoaPods..."
            gem install cocoapods
          fi
          
          # Executar pod install
          pod install --verbose
          
          echo "✅ CocoaPods instalado com sucesso!"
          
      - name: Verificar estrutura após pod install
        script: |
          cd ios
          
          echo "🔍 Verificando estrutura após pod install..."
          
          # Verificar se workspace foi criado
          if [ -f "modamaskavo.xcworkspace/contents.xcworkspacedata" ]; then
            echo "✅ Workspace criado com sucesso!"
          else
            echo "❌ Workspace não foi criado!"
            exit 1
          fi
          
          # Verificar se Pods foram instalados
          if [ -d "Pods" ]; then
            echo "✅ Pasta Pods criada!"
            echo "📁 Pods instalados:"
            ls -la Pods/ | head -10
          else
            echo "❌ Pasta Pods não encontrada!"
            exit 1
          fi
          
          # Verificar se React foi instalado
          if [ -d "Pods/React-Core" ] || [ -d "Pods/React" ]; then
            echo "✅ React encontrado nos Pods!"
          else
            echo "❌ React não encontrado nos Pods!"
            echo "📁 Pods disponíveis:"
            ls -la Pods/ | grep -i react || echo "Nenhum pod React encontrado"
          fi
          
      - name: Build iOS com workspace
        script: |
          cd ios
          
          mkdir -p build
          
          echo "🔨 Iniciando build com workspace..."
          
          # Build usando WORKSPACE (não project) para React Native
          xcodebuild -workspace modamaskavo.xcworkspace \
                     -scheme modamaskavo \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build/modamaskavo.xcarchive \
                     archive \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     SKIP_INSTALL=NO \
                     ONLY_ACTIVE_ARCH=NO \
                     -allowProvisioningUpdates \
                     2>&1 | tee build-success.log
          
          BUILD_RESULT=$?
          
          echo ""
          echo "📊 Resultado do build: $BUILD_RESULT"
          
          if [ $BUILD_RESULT -eq 0 ]; then
            echo "✅ BUILD SUCESSO!"
            
            # Verificar se archive foi criado
            if [ -d "build/modamaskavo.xcarchive" ]; then
              echo "✅ Archive criado com sucesso!"
              
              # Mostrar tamanho do archive
              ARCHIVE_SIZE=$(du -sh build/modamaskavo.xcarchive | cut -f1)
              echo "📊 Tamanho do archive: $ARCHIVE_SIZE"
              
              # Procurar por .app
              echo "📱 Procurando .app no archive:"
              find build/modamaskavo.xcarchive -name "*.app" -type d -exec ls -lah {} \;
              
            else
              echo "❌ Archive não foi criado!"
            fi
          else
            echo "❌ Build falhou!"
            echo "🔍 Últimas linhas do erro:"
            tail -50 build-success.log
          fi
          
      - name: Criar IPA do archive
        script: |
          cd ios
          
          echo "📦 Criando IPA do archive..."
          
          # Verificar se archive existe
          if [ -d "build/modamaskavo.xcarchive" ]; then
            echo "✅ Archive encontrado!"
            
            # Procurar por .app no archive
            APP_PATH=$(find build/modamaskavo.xcarchive -name "*.app" -type d | head -1)
            
            if [ -n "$APP_PATH" ]; then
              echo "📱 App encontrado: $APP_PATH"
              
              # Verificar tamanho do app
              APP_SIZE=$(du -sh "$APP_PATH" | cut -f1)
              FILE_COUNT=$(find "$APP_PATH" -type f | wc -l)
              
              echo "📊 Tamanho do app: $APP_SIZE"
              echo "📄 Número de arquivos: $FILE_COUNT"
              
              # Listar alguns arquivos para verificar se está completo
              echo "📄 Alguns arquivos do app:"
              find "$APP_PATH" -type f | head -10
              
              # Criar IPA
              cd build
              
              # Copiar .app
              cp -r "$APP_PATH" ./modamaskavo.app
              
              # Criar estrutura IPA
              mkdir -p Payload
              cp -r modamaskavo.app Payload/
              
              # Criar ZIP/IPA
              zip -r modamaskavo.ipa Payload/
              
              # Verificar IPA criado
              if [ -f "modamaskavo.ipa" ]; then
                IPA_SIZE=$(du -sh modamaskavo.ipa | cut -f1)
                IPA_BYTES=$(wc -c < modamaskavo.ipa)
                
                echo "✅ IPA criado com sucesso!"
                echo "📊 Tamanho do IPA: $IPA_SIZE ($IPA_BYTES bytes)"
                
                # Copiar para raiz
                cp modamaskavo.ipa ../../modamaskavo-react-native.ipa
                
                if [ $IPA_BYTES -gt 5000000 ]; then  # Maior que 5MB
                  echo "🎉 IPA parece válido para React Native!"
                else
                  echo "⚠️  IPA ainda pequeno para React Native"
                fi
                
                # Verificar conteúdo do IPA
                echo "📄 Verificando conteúdo do IPA:"
                unzip -l modamaskavo.ipa | head -20
                
              else
                echo "❌ Falha ao criar IPA!"
              fi
            else
              echo "❌ Nenhum .app encontrado no archive!"
            fi
          else
            echo "❌ Archive não existe!"
          fi
          
      - name: Relatório final
        script: |
          echo "📋 RELATÓRIO FINAL"
          echo "=================="
          
          # Verificar IPAs criados
          echo "📱 IPAs encontrados:"
          find . -name "*.ipa" -exec ls -lh {} \;
          
          # Verificar se build foi bem-sucedido
          if [ -f "ios/build-success.log" ]; then
            echo ""
            echo "📊 Status do build:"
            if grep -q "BUILD SUCCEEDED" ios/build-success.log; then
              echo "✅ Build bem-sucedido!"
            else
              echo "❌ Build falhou"
            fi
          fi
          
          # Verificar se CocoaPods funcionou
          echo ""
          echo "📊 Status CocoaPods:"
          if [ -f "ios/Podfile.lock" ]; then
            echo "✅ Podfile.lock encontrado"
          else
            echo "❌ Podfile.lock não encontrado"
          fi
          
          if [ -d "ios/Pods" ]; then
            echo "✅ Pods instalados"
          else
            echo "❌ Pods não instalados"
          fi
          
    artifacts:
      - ios/build/*.ipa
      - ios/build/*.app
      - ios/build/*.xcarchive
      - ios/build-success.log
      - ios/Podfile.lock
      - "*.ipa"
