# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_SCHEME: 'modamaskavo'

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install

      - name: Build iOS app (Debug mode)
        script: |
          cd ios
          if [ -d "modamaskavo.xcworkspace" ]; then
            xcodebuild -workspace modamaskavo.xcworkspace \
              -scheme "$XCODE_SCHEME" \
              -configuration Debug \
              -destination generic/platform=iOS \
              -sdk iphoneos \
              CODE_SIGNING_ALLOWED=NO \
              build
          else
            xcodebuild -project modamaskavo.xcodeproj \
              -scheme "$XCODE_SCHEME" \
              -configuration Debug \
              -destination generic/platform=iOS \
              -sdk iphoneos \
              CODE_SIGNING_ALLOWED=NO \
              build
          fi

    artifacts:
      - /tmp/xcodebuild_logs/*.log
