# codemagic.yaml - SOLUÇÃO FINAL DEFINITIVA
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: DESTRUIR RuntimeApple COMPLETAMENTE
        script: |
          # 1. DELETAR o diretório físico
          rm -rf node_modules/react-native/ReactCommon/react/runtime
          
          # 2. REESCREVER o react_native_pods.rb usando Python (mais confiável)
          python3 << 'EOF'
          import re
          
          # Ler o arquivo original
          with open('node_modules/react-native/scripts/react_native_pods.rb', 'r') as f:
              content = f.read()
          
          # Remover todas as linhas que contêm RuntimeApple ou RCTRuntime
          lines = content.split('\n')
          filtered_lines = []
          
          for line in lines:
              if 'RuntimeApple' not in line and 'RCTRuntime' not in line:
                  filtered_lines.append(line)
          
          # Escrever o arquivo modificado
          with open('node_modules/react-native/scripts/react_native_pods.rb', 'w') as f:
              f.write('\n'.join(filtered_lines))
          
          print("✅ RuntimeApple removido com Python!")
          EOF
          
          # 3. Verificar se foi removido
          echo "=== Verificando remoção ==="
          if grep -q "RuntimeApple" node_modules/react-native/scripts/react_native_pods.rb; then
            echo "❌ RuntimeApple ainda está lá"
            exit 1
          else
            echo "✅ RuntimeApple removido com sucesso"
          fi
          
      - name: Criar Podfile SUPER SIMPLES
        script: |
          cat > ios/Podfile << 'EOF'
          require_relative '../node_modules/react-native/scripts/react_native_pods'
          
          platform :ios, '12.0'
          
          target 'modamaskavo' do
            config = use_native_modules!
            
            use_react_native!(
              :path => config[:reactNativePath],
              :hermes_enabled => false,
              :fabric_enabled => false,
              :new_arch_enabled => false
            )
            
            post_install do |installer|
              react_native_post_install(installer)
              
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                end
              end
            end
          end
          EOF
      - name: Clean CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
