workflows:
  ios-workflow-fixed:
    name: iOS Build com Podfile Correto
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: |
          echo "📦 Instalando dependências npm..."
          npm install
          
      - name: Verificar e corrigir Podfile
        script: |
          cd ios
          
          echo "🔍 Verificando Podfile..."
          
          if [ -f "Podfile" ]; then
            echo "📄 Conteúdo atual do Podfile:"
            cat Podfile
            
            echo ""
            echo "🔧 Corrigindo deployment target no Podfile..."
            
            # Fazer backup do Podfile original
            cp Podfile Podfile.backup
            
            # Usar sed para corrigir o deployment target
            sed -i.bak "s/platform :ios, '[^']*'/platform :ios, '13.0'/" Podfile
            
            # Se não encontrou a linha platform, adicionar no início
            if ! grep -q "platform :ios" Podfile; then
              # Criar novo Podfile com platform correto
              echo "platform :ios, '13.0'" > Podfile.new
              cat Podfile >> Podfile.new
              mv Podfile.new Podfile
            fi
            
            # Verificar se tem post_install, se não tiver, adicionar
            if ! grep -q "post_install" Podfile; then
              echo "" >> Podfile
              echo "post_install do |installer|" >> Podfile
              echo "  installer.pods_project.targets.each do |target|" >> Podfile
              echo "    target.build_configurations.each do |config|" >> Podfile
              echo "      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'" >> Podfile
              echo "    end" >> Podfile
              echo "  end" >> Podfile
              echo "end" >> Podfile
            fi
            
            echo ""
            echo "📄 Podfile corrigido:"
            cat Podfile
            
          else
            echo "❌ Podfile não encontrado!"
            exit 1
          fi
          
      - name: Limpar cache e instalar CocoaPods
        script: |
          cd ios
          
          echo "🧹 Limpando cache e instalações anteriores..."
          
          # Remover instalações anteriores
          rm -rf Pods
          rm -f Podfile.lock
          
          # Limpar cache do CocoaPods
          pod cache clean --all
          
          echo "📦 Instalando CocoaPods..."
          
          # Instalar com verbose para ver o progresso
          pod install --verbose --repo-update 2>&1 | tee pod-install.log
          
          POD_RESULT=$?
          
          if [ $POD_RESULT -eq 0 ]; then
            echo "✅ CocoaPods instalado com sucesso!"
          else
            echo "❌ CocoaPods falhou!"
            echo "🔍 Últimas linhas do erro:"
            tail -30 pod-install.log
            
            # Procurar por erros específicos
            echo ""
            echo "🔍 Erros específicos:"
            grep -i "error" pod-install.log | head -5
            
            exit 1
          fi
          
      - name: Verificar instalação do CocoaPods
        script: |
          cd ios
          
          echo "🔍 Verificando instalação do CocoaPods..."
          
          # Verificar se workspace foi criado
          if [ -f "modamaskavo.xcworkspace/contents.xcworkspacedata" ]; then
            echo "✅ Workspace criado com sucesso!"
          else
            echo "❌ Workspace não foi criado!"
            exit 1
          fi
          
          # Verificar se Pods foram instalados
          if [ -d "Pods" ]; then
            echo "✅ Pasta Pods criada!"
            echo "📁 Pods principais instalados:"
            ls -la Pods/ | grep -E "(React|RN|Folly)" | head -10
          else
            echo "❌ Pasta Pods não encontrada!"
            exit 1
          fi
          
          # Verificar Podfile.lock
          if [ -f "Podfile.lock" ]; then
            echo "✅ Podfile.lock criado!"
          else
            echo "❌ Podfile.lock não encontrado!"
            exit 1
          fi
          
      - name: Build iOS com workspace
        script: |
          cd ios
          
          mkdir -p build
          
          echo "🔨 Iniciando build com workspace..."
          
          # Build usando workspace
          xcodebuild -workspace modamaskavo.xcworkspace \
                     -scheme modamaskavo \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build/modamaskavo.xcarchive \
                     archive \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     SKIP_INSTALL=NO \
                     ONLY_ACTIVE_ARCH=NO \
                     IPHONEOS_DEPLOYMENT_TARGET=13.0 \
                     -allowProvisioningUpdates \
                     2>&1 | tee build-success.log
          
          BUILD_RESULT=$?
          
          echo ""
          echo "📊 Resultado do build: $BUILD_RESULT"
          
          if [ $BUILD_RESULT -eq 0 ]; then
            echo "✅ BUILD SUCESSO!"
            
            # Verificar se archive foi criado
            if [ -d "build/modamaskavo.xcarchive" ]; then
              echo "✅ Archive criado!"
              
              # Procurar por .app
              APP_PATH=$(find build/modamaskavo.xcarchive -name "*.app" -type d | head -1)
              
              if [ -n "$APP_PATH" ]; then
                echo "📱 App encontrado: $APP_PATH"
                
                # Criar IPA
                cd build
                cp -r "$APP_PATH" ./modamaskavo.app
                mkdir -p Payload
                cp -r modamaskavo.app Payload/
                zip -r modamaskavo.ipa Payload/
                
                if [ -f "modamaskavo.ipa" ]; then
                  IPA_SIZE=$(du -sh modamaskavo.ipa | cut -f1)
                  echo "✅ IPA criado: $IPA_SIZE"
                  cp modamaskavo.ipa ../../modamaskavo-final.ipa
                fi
              fi
            fi
          else
            echo "❌ Build falhou!"
            tail -30 build-success.log
          fi
          
      - name: Relatório final
        script: |
          echo "📋 RELATÓRIO FINAL"
          echo "=================="
          
          echo "📱 IPAs encontrados:"
          find . -name "*.ipa" -exec ls -lh {} \;
          
    artifacts:
      - ios/build/*.ipa
      - ios/build/*.app
      - ios/build/*.xcarchive
      - ios/build-success.log
      - ios/pod-install.log
      - ios/Podfile.lock
      - "*.ipa"
