# codemagic.yaml - CRIANDO TODOS OS PODS DO REACT NATIVE
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Create ALL React Native podspecs with iOS 15.0
        script: |
          # Função para criar podspecs
          create_podspec() {
            local name=$1
            local path=$2
            mkdir -p "$path"
            cat > "$path/${name}.podspec" << EOFPOD
          Pod::Spec.new do |s|
            s.name                   = "$name"
            s.version                = "1000.0.0"
            s.summary                = "Empty podspec for compatibility"
            s.homepage               = "https://reactnative.dev/"
            s.license                = "MIT"
            s.author                 = "Meta Platforms, Inc."
            s.platforms              = { :ios => "15.0" }
            s.source                 = { :path => "." }
            s.source_files           = "*.{h,m,mm,cpp,c}"
            s.header_dir             = "React"
          end
          EOFPOD
            touch "$path/dummy.cpp"
          }
          
          # Criar ReactCommon.podspec completo
          cat > node_modules/react-native/ReactCommon/ReactCommon.podspec << 'EOF'
          Pod::Spec.new do |s|
            s.name                   = "ReactCommon"
            s.version                = "1000.0.0"
            s.summary                = "ReactCommon with all subspecs"
            s.homepage               = "https://reactnative.dev/"
            s.license                = "MIT"
            s.author                 = "Meta Platforms, Inc."
            s.platforms              = { :ios => "15.0" }
            s.source                 = { :path => "." }
            s.source_files           = "**/*.{h,m,mm,cpp,c}"
            s.header_dir             = "ReactCommon"
            
            s.subspec "turbomodule" do |ss|
              ss.subspec "core" do |sss|
                sss.source_files = "**/*.{h,m,mm,cpp,c}"
                sss.header_dir = "ReactCommon"
              end
            end
          end
          EOF
          
          # Criar Yoga.podspec específico
          cat > node_modules/react-native/ReactCommon/yoga/Yoga.podspec << 'EOF'
          Pod::Spec.new do |s|
            s.name                   = "Yoga"
            s.version                = "1000.0.0"
            s.summary                = "Yoga layout engine"
            s.homepage               = "https://yogalayout.com/"
            s.license                = "MIT"
            s.author                 = "Meta Platforms, Inc."
            s.platforms              = { :ios => "15.0" }
            s.source                 = { :path => "." }
            s.source_files           = "**/*.{h,m,mm,cpp,c}"
            s.header_dir             = "yoga"
            s.public_header_files    = "**/*.h"
          end
          EOF
          
          # Criar TODOS os podspecs problemáticos do React Native
          create_podspec "React-logger" "node_modules/react-native/ReactCommon/logger"
          create_podspec "React-oscompat" "node_modules/react-native/ReactCommon/oscompat"
          create_podspec "React-RuntimeApple" "node_modules/react-native/ReactCommon/react/runtime/platform/ios"
          create_podspec "React-RuntimeCore" "node_modules/react-native/ReactCommon/react/runtime"
          create_podspec "React-NativeModulesApple" "node_modules/react-native/ReactCommon/react/nativemodule/core/platform/ios"
          create_podspec "React-RCTNetwork" "node_modules/react-native/Libraries/Network"
          create_podspec "FBLazyVector" "node_modules/react-native/Libraries/FBLazyVector"
          create_podspec "React-Core" "node_modules/react-native/React"
          create_podspec "React-CoreModules" "node_modules/react-native/React/CoreModules"
          create_podspec "React-RCTAppDelegate" "node_modules/react-native/Libraries/AppDelegate"
          create_podspec "React-RCTImage" "node_modules/react-native/Libraries/Image"
          create_podspec "React-RCTText" "node_modules/react-native/Libraries/Text"
          create_podspec "React-RCTVibration" "node_modules/react-native/Libraries/Vibration"
          create_podspec "React-RCTLinking" "node_modules/react-native/Libraries/LinkingIOS"
          create_podspec "React-RCTSettings" "node_modules/react-native/Libraries/Settings"
          create_podspec "React-RCTBlob" "node_modules/react-native/Libraries/Blob"
          create_podspec "React-RCTAnimation" "node_modules/react-native/Libraries/NativeAnimation"
          create_podspec "React-jsi" "node_modules/react-native/ReactCommon/jsi"
          create_podspec "React-jsiexecutor" "node_modules/react-native/ReactCommon/jsiexecutor"
          create_podspec "React-jsinspector" "node_modules/react-native/ReactCommon/jsinspector"
          create_podspec "React-callinvoker" "node_modules/react-native/ReactCommon/callinvoker"
          create_podspec "React-runtimeexecutor" "node_modules/react-native/ReactCommon/runtimeexecutor"
          create_podspec "React-perflogger" "node_modules/react-native/ReactCommon/reactperflogger"
          create_podspec "React-cxxreact" "node_modules/react-native/ReactCommon/cxxreact"
          create_podspec "React-hermes" "node_modules/react-native/ReactCommon/hermes"
          create_podspec "React-utils" "node_modules/react-native/ReactCommon/react/utils"
          create_podspec "React-debug" "node_modules/react-native/ReactCommon/react/debug"
          create_podspec "React-Mapbuffer" "node_modules/react-native/ReactCommon/react/renderer/mapbuffer"
          
          echo "✅ TODOS os podspecs do React Native criados!"
          
      - name: Create Podfile with iOS 15.0
        script: |
          cat > ios/Podfile << 'EOF'
          require_relative '../node_modules/react-native/scripts/react_native_pods'
          
          platform :ios, '15.0'
          
          target 'modamaskavo' do
            config = use_native_modules!
            
            use_react_native!(
              :path => config[:reactNativePath],
              :hermes_enabled => false,
              :fabric_enabled => false,
              :new_arch_enabled => false
            )
            
            post_install do |installer|
              react_native_post_install(installer)
              
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
                  config.build_settings['RCT_NEW_ARCH_ENABLED'] = 'NO'
                end
              end
            end
          end
          EOF
      - name: Clean everything
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          rm -rf build
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
