workflows:
  ios-workflow-fixed-podfile:
    name: iOS Build com Podfile Ruby Correto
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: |
          echo "📦 Instalando dependências npm..."
          npm install
          
      - name: Verificar e corrigir Podfile
        script: |
          cd ios
          
          echo "🔍 Verificando Podfile..."
          
          if [ -f "Podfile" ]; then
            echo "📄 Conteúdo atual do Podfile:"
            cat Podfile
            
            echo ""
            echo "🔧 Corrigindo deployment target no Podfile..."
            
            # Fazer backup do Podfile original
            cp Podfile Podfile.backup
            
            # Criar um novo Podfile com sintaxe Ruby correta
            cat > Podfile << 'EOF'
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'modamaskavo' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'modamaskavoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    # Forçar deployment target em todos os pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
EOF
            
            echo ""
            echo "📄 Podfile corrigido:"
            cat Podfile
            
          else
            echo "❌ Podfile não encontrado!"
            exit 1
          fi
          
      - name: Limpar cache e instalar CocoaPods
        script: |
          cd ios
          
          echo "🧹 Limpando cache e instalações anteriores..."
          
          # Remover instalações anteriores
          rm -rf Pods
          rm -f Podfile.lock
          
          # Limpar cache do CocoaPods
          pod cache clean --all
          
          echo "📦 Instalando CocoaPods..."
          
          # Instalar com verbose para ver o progresso
          pod install --verbose --repo-update 2>&1 | tee pod-install.log
          
          POD_RESULT=$?
          
          if [ $POD_RESULT -eq 0 ]; then
            echo "✅ CocoaPods instalado com sucesso!"
          else
            echo "❌ CocoaPods falhou!"
            echo "🔍 Últimas linhas do erro:"
            tail -30 pod-install.log
            
            # Procurar por erros específicos
            echo ""
            echo "🔍 Erros específicos:"
            grep -i "error" pod-install.log | head -5
            
            exit 1
          fi
          
      - name: Verificar instalação do CocoaPods
        script: |
          cd ios
          
          echo "🔍 Verificando instalação do CocoaPods..."
          
          # Verificar se workspace foi criado
          if [ -f "modamaskavo.xcworkspace/contents.xcworkspacedata" ]; then
            echo "✅ Workspace criado com sucesso!"
          else
            echo "❌ Workspace não foi criado!"
            
            # Verificar se existe algum workspace
            find . -name "*.xcworkspace" -type d -exec echo "Workspace encontrado: {}" \;
            exit 1
          fi
          
          # Verificar se Pods foram instalados
          if [ -d "Pods" ]; then
            echo "✅ Pasta Pods criada!"
            echo "📁 Pods principais instalados:"
            ls -la Pods/ | grep -E "(React|RN|Folly)" | head -10
          else
            echo "❌ Pasta Pods não encontrada!"
            exit 1
          fi
          
          # Verificar Podfile.lock
          if [ -f "Podfile.lock" ]; then
            echo "✅ Podfile.lock criado!"
            echo "📊 Verificando deployment target:"
            grep -A 2 -B 2 "13.0" Podfile.lock | head -10
          else
            echo "❌ Podfile.lock não encontrado!"
            exit 1
          fi
          
      - name: Build iOS com workspace
        script: |
          cd ios
          
          mkdir -p build
          
          echo "🔨 Iniciando build com workspace..."
          
          # Build usando workspace
          xcodebuild -workspace modamaskavo.xcworkspace \
                     -scheme modamaskavo \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build/modamaskavo.xcarchive \
                     archive \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     SKIP_INSTALL=NO \
                     ONLY_ACTIVE_ARCH=NO \
                     IPHONEOS_DEPLOYMENT_TARGET=13.0 \
                     -allowProvisioningUpdates \
                     2>&1 | tee build-success.log
          
          BUILD_RESULT=$?
          
          echo ""
          echo "📊 Resultado do build: $BUILD_RESULT"
          
          if [ $BUILD_RESULT -eq 0 ]; then
            echo "✅ BUILD SUCESSO!"
            
            # Verificar se archive foi criado
            if [ -d "build/modamaskavo.xcarchive" ]; then
              echo "✅ Archive criado com sucesso!"
              
              # Mostrar tamanho do archive
              ARCHIVE_SIZE=$(du -sh build/modamaskavo.xcarchive | cut -f1)
              echo "📊 Tamanho do archive: $ARCHIVE_SIZE"
              
              # Procurar por .app
              echo "📱 Procurando .app no archive:"
              find build/modamaskavo.xcarchive -name "*.app" -type d -exec ls -lah {} \;
              
            else
              echo "❌ Archive não foi criado!"
            fi
          else
            echo "❌ Build falhou!"
            echo "🔍 Últimas linhas do erro:"
            tail -50 build-success.log
            
            # Procurar por erros específicos
            echo ""
            echo "🔍 Erros de deployment target:"
            grep -i "deployment" build-success.log | head -5
            
            echo ""
            echo "🔍 Outros erros:"
            grep -i "error:" build-success.log | head -10
          fi
          
      - name: Criar IPA do archive
        script: |
          cd ios
          
          echo "📦 Criando IPA do archive..."
          
          # Verificar se archive existe
          if [ -d "build/modamaskavo.xcarchive" ]; then
            echo "✅ Archive encontrado!"
            
            # Procurar por .app no archive
            APP_PATH=$(find build/modamaskavo.xcarchive -name "*.app" -type d | head -1)
            
            if [ -n "$APP_PATH" ]; then
              echo "📱 App encontrado: $APP_PATH"
              
              # Verificar tamanho do app
              APP_SIZE=$(du -sh "$APP_PATH" | cut -f1)
              FILE_COUNT=$(find "$APP_PATH" -type f | wc -l)
              
              echo "📊 Tamanho do app: $APP_SIZE"
              echo "📄 Número de arquivos: $FILE_COUNT"
              
              # Verificar se app tem conteúdo React Native
              echo "📱 Verificando conteúdo React Native:"
              find "$APP_PATH" -name "*React*" -o -name "*RN*" -o -name "*Hermes*" | head -5
              
              # Criar IPA
              cd build
              
              # Copiar .app
              cp -r "$APP_PATH" ./modamaskavo.app
              
              # Criar estrutura IPA
              mkdir -p Payload
              cp -r modamaskavo.app Payload/
              
              # Criar ZIP/IPA
              zip -r modamaskavo.ipa Payload/
              
              # Verificar IPA criado
              if [ -f "modamaskavo.ipa" ]; then
                IPA_SIZE=$(du -sh modamaskavo.ipa | cut -f1)
                IPA_BYTES=$(wc -c < modamaskavo.ipa)
                
                echo "✅ IPA criado com sucesso!"
                echo "📊 Tamanho do IPA: $IPA_SIZE ($IPA_BYTES bytes)"
                
                # Copiar para raiz
                cp modamaskavo.ipa ../../modamaskavo-react-native.ipa
                
                if [ $IPA_BYTES -gt 10000000 ]; then  # Maior que 10MB
                  echo "🎉 IPA parece válido para React Native!"
                else
                  echo "⚠️  IPA pequeno, mas foi criado"
                fi
                
                # Verificar conteúdo do IPA
                echo "📄 Estrutura do IPA:"
                unzip -l modamaskavo.ipa | head -20
                
              else
                echo "❌ Falha ao criar IPA!"
              fi
            else
              echo "❌ Nenhum .app encontrado no archive!"
              echo "📁 Conteúdo do archive:"
              find build/modamaskavo.xcarchive -type f | head -10
            fi
          else
            echo "❌ Archive não existe - build falhou!"
          fi
          
      - name: Relatório final
        script: |
          echo "📋 RELATÓRIO FINAL"
          echo "=================="
          
          # Verificar IPAs criados
          echo "📱 IPAs encontrados:"
          find . -name "*.ipa" -exec ls -lh {} \;
          
          # Status do build
          echo ""
          echo "📊 Status do build:"
          if [ -f "ios/build-success.log" ]; then
            if grep -q "BUILD SUCCEEDED" ios/build-success.log; then
              echo "✅ Build bem-sucedido!"
            else
              echo "❌ Build falhou"
            fi
          fi
          
          # Status do CocoaPods
          echo ""
          echo "📊 Status CocoaPods:"
          if [ -f "ios/Podfile.lock" ]; then
            echo "✅ Podfile.lock criado"
          else
            echo "❌ Podfile.lock não encontrado"
          fi
          
          # Status do workspace
          if [ -f "ios/modamaskavo.xcworkspace/contents.xcworkspacedata" ]; then
            echo "✅ Workspace criado"
          else
            echo "❌ Workspace não criado"
          fi
          
    artifacts:
      - ios/build/*.ipa
      - ios/build/*.app
      - ios/build/*.xcarchive
      - ios/build-success.log
      - ios/pod-install.log
      - ios/Podfile.lock
      - ios/Podfile.backup
      - "*.ipa"
