# codemagic.yaml
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
        RCT_NEW_ARCH_ENABLED: 0
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Hack React Native Pods
        script: |
          # Backup original
          cp node_modules/react-native/scripts/react_native_pods.rb node_modules/react-native/scripts/react_native_pods.rb.backup
          
          # Remove todas as referências ao RuntimeApple
          sed -i '' '/RuntimeApple/d' node_modules/react-native/scripts/react_native_pods.rb
          sed -i '' '/React-RCTRuntime/d' node_modules/react-native/scripts/react_native_pods.rb
          
          # Verificar o que foi removido
          echo "=== Verificando remoções ==="
          grep -n "Runtime" node_modules/react-native/scripts/react_native_pods.rb || echo "Runtime removido com sucesso"
          
      - name: Create .xcode.env
        script: |
          echo "export RCT_NEW_ARCH_ENABLED=0" > ios/.xcode.env
          echo "export NODE_BINARY=node" >> ios/.xcode.env
      - name: Clean CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
