# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: Techmitz

    environment:
      groups:
        - apple_developer_portal_credentials
      vars:
        XCODE_SCHEME: 'modamaskavo'

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods
          rm -f Podfile.lock
          pod install

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files com.modamaskavo \
            --type IOS_APP_STORE \
            --create

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          if [ -d "ios/modamaskavo.xcworkspace" ]; then
            xcode-project build-ipa \
              --workspace "ios/modamaskavo.xcworkspace" \
              --scheme "$XCODE_SCHEME"
          else
            xcode-project build-ipa \
              --project "ios/modamaskavo.xcodeproj" \
              --scheme "$XCODE_SCHEME"
          fi

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
