# codemagic.yaml - SOLUÇÃO DEFINITIVA (DE VERDADE)
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: PATCH React Native Pods (Cirúrgico)
        script: |
          # Backup do arquivo original
          cp node_modules/react-native/scripts/react_native_pods.rb node_modules/react-native/scripts/react_native_pods.rb.backup
          
          # Remover SOMENTE as linhas do RuntimeApple
          sed -i '' '/React-RuntimeApple/d' node_modules/react-native/scripts/react_native_pods.rb
          sed -i '' '/React-RCTRuntime/d' node_modules/react-native/scripts/react_native_pods.rb
          
          # Verificar se foi removido
          echo "=== Verificando se Runtime foi removido ==="
          if grep -q "RuntimeApple" node_modules/react-native/scripts/react_native_pods.rb; then
            echo "❌ RuntimeApple ainda está lá"
          else
            echo "✅ RuntimeApple removido com sucesso"
          fi
          
          # Mostrar as linhas que contêm "pod" para debug
          echo "=== Pods restantes ==="
          grep "pod '" node_modules/react-native/scripts/react_native_pods.rb | head -10
          
      - name: Criar Podfile COMPATÍVEL
        script: |
          cat > ios/Podfile << 'EOF'
          require_relative '../node_modules/react-native/scripts/react_native_pods'
          
          platform :ios, '12.0'
          
          target 'modamaskavo' do
            config = use_native_modules!
            
            use_react_native!(
              :path => config[:reactNativePath],
              :hermes_enabled => false,
              :fabric_enabled => false,
              :new_arch_enabled => false
            )
            
            post_install do |installer|
              react_native_post_install(installer)
              
              # Forçar iOS 12.0 em todos os pods
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                end
              end
            end
          end
          EOF
      - name: Clean CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
