# codemagic.yaml - SOLUÇÃO DEFINITIVA PARA TODOS OS PODSPECS
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: HACK DEFINITIVO - Forçar iOS 15.0 em TODOS os podspecs
        script: |
          # Encontrar e modificar TODOS os podspecs do React Native
          find node_modules/react-native -name "*.podspec" -type f | while read podspec; do
            echo "Modificando $podspec"
            # Substituir qualquer versão iOS por 15.0
            sed -i '' 's/s\.platforms.*=.*{.*:ios.*=>.*/s.platforms = { :ios => "15.0" }/' "$podspec"
            sed -i '' 's/ios\.deployment_target.*=.*/ios.deployment_target = "15.0"/' "$podspec"
            sed -i '' 's/spec\.ios\.deployment_target.*=.*/spec.ios.deployment_target = "15.0"/' "$podspec"
          done
          
          # Fazer o mesmo para node_modules de terceiros
          find node_modules -name "*.podspec" -type f | while read podspec; do
            echo "Modificando $podspec"
            sed -i '' 's/s\.platforms.*=.*{.*:ios.*=>.*/s.platforms = { :ios => "15.0" }/' "$podspec"
            sed -i '' 's/ios\.deployment_target.*=.*/ios.deployment_target = "15.0"/' "$podspec"
            sed -i '' 's/spec\.ios\.deployment_target.*=.*/spec.ios.deployment_target = "15.0"/' "$podspec"
          done
          
          echo "✅ TODOS os podspecs modificados para iOS 15.0!"
          
      - name: Create Podfile with iOS 15.0
        script: |
          cat > ios/Podfile << 'EOF'
          require_relative '../node_modules/react-native/scripts/react_native_pods'
          
          platform :ios, '15.0'
          
          target 'modamaskavo' do
            config = use_native_modules!
            
            use_react_native!(
              :path => config[:reactNativePath],
              :hermes_enabled => false,
              :fabric_enabled => false,
              :new_arch_enabled => false
            )
            
            post_install do |installer|
              react_native_post_install(installer)
              
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
                  config.build_settings['RCT_NEW_ARCH_ENABLED'] = 'NO'
                end
              end
            end
          end
          EOF
      - name: Clean everything
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          rm -rf build
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
