workflows:
  ios-workflow:
    name: iOS Simple Build
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          
      - name: Simple Podfile
        script: |
          cat > ios/Podfile << 'EOF'
          platform :ios, '13.0'
          target 'modamaskavo' do
            pod 'React', :path => '../node_modules/react-native'
            pod 'React-Core', :path => '../node_modules/react-native'
          end
          EOF
          
      - name: Pod install
        script: |
          cd ios && pod install
          
      - name: Build
        script: |
          cd ios
          xcodebuild -workspace modamaskavo.xcworkspace -scheme modamaskavo -configuration Release -destination generic/platform=iOS archive -archivePath build/app.xcarchive
          xcodebuild -exportArchive -archivePath build/app.xcarchive -exportPath build -exportOptionsPlist ../exportOptions.plist
          
    artifacts:
      - ios/build/*.ipa
