# codemagic.yaml
workflows:
  ios-build:
    name: iOS Build (Expo-like)
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_SCHEME: 'modamaskavo'

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Setup environment (Expo-like)
        script: |
          cd ios
          cat > .xcode.env << EOF
          export NODE_BINARY=node
          export RCT_NEW_ARCH_ENABLED=0
          export RCT_FABRIC_ENABLED=0
          export HERMES_ENABLED=0
          EOF

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          # Usar --repo-update para garantir versões compatíveis
          pod install --repo-update --verbose

      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -workspace modamaskavo.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO \
            VALID_ARCHS=arm64 \
            IPHONEOS_DEPLOYMENT_TARGET=11.0 \
            RCT_NEW_ARCH_ENABLED=0 \
            build

    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - ios/build/Build/Products/Release-iphoneos/*.app
