# codemagic.yaml - TENTATIVA FINAL
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Force disable New Architecture EVERYWHERE
        script: |
          # Criar .xcode.env forçando old arch
          echo "export RCT_NEW_ARCH_ENABLED=0" > ios/.xcode.env
          echo "export NODE_BINARY=node" >> ios/.xcode.env
          
          # Forçar no package.json
          node -e "
          const pkg = require('./package.json');
          pkg.codegenConfig = pkg.codegenConfig || {};
          pkg.codegenConfig.libraries = [];
          require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2));
          "
          
          # Deletar TUDO relacionado ao runtime
          rm -rf node_modules/react-native/ReactCommon/react/runtime
          rm -rf ios/build/generated
          
      - name: Create minimal Podfile
        script: |
          cat > ios/Podfile << 'EOF'
          require_relative '../node_modules/react-native/scripts/react_native_pods'
          
          platform :ios, '15.0'
          
          target 'modamaskavo' do
            config = use_native_modules!
            
            # Forçar old architecture
            use_react_native!(
              :path => config[:reactNativePath],
              :hermes_enabled => false,
              :fabric_enabled => false,
              :new_arch_enabled => false,
              :flipper_configuration => FlipperConfiguration.disabled
            )
            
            post_install do |installer|
              react_native_post_install(installer)
              
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
                  config.build_settings['RCT_NEW_ARCH_ENABLED'] = 'NO'
                end
              end
            end
          end
          EOF
      - name: Clean everything
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          rm -rf build
          rm -rf DerivedData
      - name: Install CocoaPods dependencies
        script: |
          cd ios && RCT_NEW_ARCH_ENABLED=0 pod install
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
