# codemagic.yaml
# Este arquivo define o fluxo de build para o CodeMagic

workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1 # ou mac_mini_m2, dependendo da sua necessidade e plano

    # Removendo o bloco 'integrations' pois a conexão GitHub já é feita na UI do CodeMagic
    # integrations:
    #   github:
    #     integration_id: SEU_ID_AQUI # Esta linha não é necessária se a integração já foi feita na UI

    environment:
      # Versão do Node.js que seu projeto usa (verifique seu package.json ou use a que funciona localmente)
      node: lts
      # Versão do Ruby para CocoaPods (geralmente a padrão do CodeMagic funciona bem)
      ruby: 3.x
      # Grupo de variáveis de ambiente para credenciais de assinatura (configurado no CodeMagic UI)
      groups:
        - apple_developer_portal_credentials # Certifique-se de que este nome corresponde ao que você configurou
      vars:
        # Nome do seu esquema Xcode (geralmente o nome do projeto)
        XCODE_SCHEME: 'modamaskavo'
        # Não precisamos de XCODE_WORKSPACE aqui, vamos detectá-lo no script de build

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          # Verifica se o .xcworkspace existe (gerado pelo pod install)
          if [ -d "ios/modamaskavo.xcworkspace" ]; then
            echo "Usando .xcworkspace"
            xcode-project build-ipa \
              --workspace "ios/modamaskavo.xcworkspace" \
              --scheme "$XCODE_SCHEME"
          elif [ -d "ios/modamaskavo.xcodeproj" ]; then
            echo "Usando .xcodeproj"
            xcode-project build-ipa \
              --project "ios/modamaskavo.xcodeproj" \
              --scheme "$XCODE_SCHEME"
          else
            echo "Erro: Não foi encontrado .xcworkspace nem .xcodeproj na pasta ios/"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    # Removendo o bloco 'publishing' para evitar o erro 'none is not an allowed value'
    # Se você quiser configurar a publicação, adicione o bloco completo aqui com as configurações corretas.
    # publishing:
    #   apple_app_store:
    #     api_key:
    #       id: Encrypted
    #       issuer_id: Encrypted
    #     track: TestFlight
    #     submit_for_review: false
    #     automatic_release: false
