workflows:
  ios-workflow-final:
    name: iOS Build - Solução Final
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: |
          echo "📦 Instalando dependências npm..."
          npm install
          
      - name: Verificar e corrigir deployment target
        script: |
          cd ios
          
          echo "🔍 Verificando Podfile original..."
          if [ -f "Podfile" ]; then
            cat Podfile
            
            echo ""
            echo "🔧 Corrigindo deployment target para iOS 13.0..."
            
            # Backup
            cp Podfile Podfile.backup
            
            # Forçar iOS 13.0 como deployment target
            sed -i.bak "s/platform :ios, '[^']*'/platform :ios, '13.0'/" Podfile
            
            # Se não encontrou a linha, adicionar
            if ! grep -q "platform :ios" Podfile; then
              echo "platform :ios, '13.0'" > Podfile.new
              cat Podfile >> Podfile.new
              mv Podfile.new Podfile
            fi
            
            # Garantir que post_install existe para forçar deployment target
            if ! grep -q "post_install" Podfile; then
              echo "" >> Podfile
              echo "post_install do |installer|" >> Podfile
              echo "  installer.pods_project.targets.each do |target|" >> Podfile
              echo "    target.build_configurations.each do |config|" >> Podfile
              echo "      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'" >> Podfile
              echo "    end" >> Podfile
              echo "  end" >> Podfile
              echo "end" >> Podfile
            fi
            
            echo ""
            echo "📄 Podfile corrigido:"
            cat Podfile
          fi
          
      - name: Instalar CocoaPods com deployment target correto
        script: |
          cd ios
          
          echo "🧹 Limpando instalações anteriores..."
          rm -rf Pods
          rm -f Podfile.lock
          pod cache clean --all
          
          echo "📦 Instalando CocoaPods com iOS 13.0..."
          pod install --verbose --repo-update
          
          if [ $? -eq 0 ]; then
            echo "✅ CocoaPods instalado com sucesso!"
          else
            echo "❌ CocoaPods falhou! Tentando com deployment target explícito..."
            
            # Última tentativa com deployment target explícito
            IPHONEOS_DEPLOYMENT_TARGET=13.0 pod install --verbose --repo-update
            
            if [ $? -ne 0 ]; then
              echo "❌ Falha total no CocoaPods!"
              exit 1
            fi
          fi
          
      - name: Verificar se workspace foi criado
        script: |
          cd ios
          
          if [ -f "modamaskavo.xcworkspace/contents.xcworkspacedata" ]; then
            echo "✅ Workspace criado com sucesso!"
          else
            echo "❌ Workspace não foi criado!"
            exit 1
          fi
          
          if [ -d "Pods" ]; then
            echo "✅ Pods instalados!"
            echo "📁 Principais pods:"
            ls -la Pods/ | grep -E "(React|RN)" | head -5
          else
            echo "❌ Pods não instalados!"
            exit 1
          fi
          
      - name: Build iOS com workspace
        script: |
          cd ios
          
          mkdir -p build
          
          echo "🔨 Iniciando build com workspace..."
          
          xcodebuild -workspace modamaskavo.xcworkspace \
                     -scheme modamaskavo \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build/modamaskavo.xcarchive \
                     archive \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     SKIP_INSTALL=NO \
                     ONLY_ACTIVE_ARCH=NO \
                     IPHONEOS_DEPLOYMENT_TARGET=13.0 \
                     -allowProvisioningUpdates
          
          if [ $? -eq 0 ]; then
            echo "✅ Build bem-sucedido!"
            
            # Procurar .app
            APP_PATH=$(find build/modamaskavo.xcarchive -name "*.app" -type d | head -1)
            
            if [ -n "$APP_PATH" ]; then
              echo "📱 App encontrado: $APP_PATH"
              
              # Verificar tamanho
              APP_SIZE=$(du -sh "$APP_PATH" | cut -f1)
              echo "📊 Tamanho do app: $APP_SIZE"
              
              # Criar IPA
              cd build
              cp -r "$APP_PATH" ./modamaskavo.app
              mkdir -p Payload
              cp -r modamaskavo.app Payload/
              zip -r modamaskavo.ipa Payload/
              
              if [ -f "modamaskavo.ipa" ]; then
                IPA_SIZE=$(du -sh modamaskavo.ipa | cut -f1)
                IPA_BYTES=$(wc -c < modamaskavo.ipa)
                
                echo "✅ IPA criado com sucesso!"
                echo "📊 Tamanho do IPA: $IPA_SIZE ($IPA_BYTES bytes)"
                
                cp modamaskavo.ipa ../../modamaskavo-final.ipa
                
                if [ $IPA_BYTES -gt 10000000 ]; then
                  echo "🎉 IPA válido para React Native!"
                else
                  echo "⚠️  IPA pequeno, mas foi criado"
                fi
              fi
            fi
          else
            echo "❌ Build falhou!"
          fi
          
      - name: Relatório final
        script: |
          echo "📋 RELATÓRIO FINAL"
          echo "=================="
          
          echo "📱 IPAs encontrados:"
          find . -name "*.ipa" -exec ls -lh {} \;
          
          echo ""
          echo "📊 Status:"
          echo "- Podfile corrigido: ✅"
          echo "- CocoaPods instalado: $([ -d "ios/Pods" ] && echo "✅" || echo "❌")"
          echo "- Workspace criado: $([ -f "ios/modamaskavo.xcworkspace/contents.xcworkspacedata" ] && echo "✅" || echo "❌")"
          echo "- Build realizado: $([ -d "ios/build" ] && echo "✅" || echo "❌")"
          
    artifacts:
      - ios/build/*.ipa
      - ios/build/*.app
      - ios/build/*.xcarchive
      - ios/Podfile.backup
      - ios/Podfile.lock
      - "*.ipa"
