workflows:
  ios-workflow-debug-pods:
    name: iOS Build - Debug CocoaPods
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: |
          echo "📦 Instalando dependências npm..."
          npm install
          
      - name: Verificar estrutura antes do pod install
        script: |
          cd ios
          
          echo "🔍 Verificando estrutura antes do pod install..."
          
          # Verificar se Podfile existe
          if [ -f "Podfile" ]; then
            echo "✅ Podfile encontrado"
            echo "📄 Conteúdo do Podfile:"
            cat Podfile
          else
            echo "❌ Podfile não encontrado!"
            echo "📁 Arquivos na pasta ios:"
            ls -la
          fi
          
          # Verificar se já existe workspace
          if [ -f "modamaskavo.xcworkspace/contents.xcworkspacedata" ]; then
            echo "✅ Workspace já existe"
          else
            echo "ℹ️  Workspace não existe ainda (normal)"
          fi
          
      - name: Install CocoaPods com diagnóstico
        script: |
          cd ios
          
          echo "📦 Instalando CocoaPods com diagnóstico..."
          
          # Verificar se CocoaPods está instalado
          if ! command -v pod &> /dev/null; then
            echo "📦 Instalando CocoaPods..."
            gem install cocoapods
          else
            echo "✅ CocoaPods já instalado"
            pod --version
          fi
          
          # Executar pod install com logs completos
          echo "🔨 Executando pod install..."
          pod install --verbose 2>&1 | tee pod-install.log
          
          POD_RESULT=$?
          
          echo ""
          echo "📊 Resultado do pod install: $POD_RESULT"
          
          if [ $POD_RESULT -eq 0 ]; then
            echo "✅ pod install executado com sucesso!"
          else
            echo "❌ pod install falhou!"
            echo "🔍 Últimas linhas do log:"
            tail -30 pod-install.log
            
            echo ""
            echo "🔍 Procurando por erros específicos:"
            grep -i "error" pod-install.log | head -5
            grep -i "could not" pod-install.log | head -5
            grep -i "unable" pod-install.log | head -5
          fi
          
      - name: Verificar o que foi criado
        script: |
          cd ios
          
          echo "🔍 Verificando o que foi criado após pod install..."
          
          # Verificar workspace
          if [ -f "modamaskavo.xcworkspace/contents.xcworkspacedata" ]; then
            echo "✅ Workspace criado!"
          else
            echo "❌ Workspace NÃO foi criado!"
            
            # Verificar se existe algum workspace
            WORKSPACES=$(find . -name "*.xcworkspace" -type d)
            if [ -n "$WORKSPACES" ]; then
              echo "📁 Workspaces encontrados:"
              echo "$WORKSPACES"
            else
              echo "❌ Nenhum workspace encontrado!"
            fi
          fi
          
          # Verificar Podfile.lock
          if [ -f "Podfile.lock" ]; then
            echo "✅ Podfile.lock criado!"
            echo "📄 Primeiras linhas do Podfile.lock:"
            head -20 Podfile.lock
          else
            echo "❌ Podfile.lock NÃO foi criado!"
          fi
          
          # Verificar pasta Pods
          if [ -d "Pods" ]; then
            echo "✅ Pasta Pods criada!"
            echo "📁 Conteúdo da pasta Pods:"
            ls -la Pods/ | head -10
          else
            echo "❌ Pasta Pods NÃO foi criada!"
          fi
          
          # Verificar se React foi instalado
          if [ -d "Pods/React-Core" ] || [ -d "Pods/React" ] || [ -d "Pods/RCT-Folly" ]; then
            echo "✅ Componentes React encontrados!"
          else
            echo "❌ Componentes React NÃO encontrados!"
            if [ -d "Pods" ]; then
              echo "📁 Pods disponíveis:"
              ls -la Pods/ | grep -v "^d.*\.$"
            fi
          fi
          
      - name: Tentar corrigir problemas comuns
        script: |
          cd ios
          
          echo "🔧 Tentando corrigir problemas comuns..."
          
          # Se pod install falhou, tentar soluções
          if [ ! -f "modamaskavo.xcworkspace/contents.xcworkspacedata" ]; then
            echo "⚠️  Workspace não foi criado, tentando soluções..."
            
            # Limpar cache do CocoaPods
            echo "🧹 Limpando cache do CocoaPods..."
            pod cache clean --all
            
            # Remover Pods e tentar novamente
            if [ -d "Pods" ]; then
              echo "🗑️  Removendo Pods existentes..."
              rm -rf Pods
            fi
            
            if [ -f "Podfile.lock" ]; then
              echo "🗑️  Removendo Podfile.lock..."
              rm -f Podfile.lock
            fi
            
            # Tentar pod install novamente
            echo "🔄 Tentando pod install novamente..."
            pod install --repo-update --verbose 2>&1 | tee pod-install-retry.log
            
            RETRY_RESULT=$?
            
            if [ $RETRY_RESULT -eq 0 ]; then
              echo "✅ pod install funcionou na segunda tentativa!"
            else
              echo "❌ pod install falhou novamente!"
              echo "🔍 Erros da segunda tentativa:"
              tail -20 pod-install-retry.log
            fi
          fi
          
      - name: Criar workspace manualmente se necessário
        script: |
          cd ios
          
          echo "🔧 Verificando se precisamos criar workspace manualmente..."
          
          if [ ! -f "modamaskavo.xcworkspace/contents.xcworkspacedata" ]; then
            echo "⚠️  Criando workspace manualmente..."
            
            # Criar estrutura do workspace
            mkdir -p modamaskavo.xcworkspace
            
            # Criar contents.xcworkspacedata
            cat > modamaskavo.xcworkspace/contents.xcworkspacedata << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <Workspace
             version = "1.0">
             <FileRef
                location = "group:modamaskavo.xcodeproj">
             </FileRef>
             <FileRef
                location = "group:Pods/Pods.xcodeproj">
             </FileRef>
          </Workspace>
          EOF
            
            echo "✅ Workspace criado manualmente!"
          else
            echo "✅ Workspace já existe!"
          fi
          
      - name: Tentar build com o que temos
        script: |
          cd ios
          
          echo "🔨 Tentando build com o que temos..."
          
          # Decidir se usar workspace ou project
          if [ -f "modamaskavo.xcworkspace/contents.xcworkspacedata" ]; then
            echo "📱 Usando workspace para build..."
            BUILD_TYPE="-workspace modamaskavo.xcworkspace"
          else
            echo "📱 Usando project para build..."
            BUILD_TYPE="-project modamaskavo.xcodeproj"
          fi
          
          mkdir -p build
          
          # Tentar build
          xcodebuild $BUILD_TYPE \
                     -scheme modamaskavo \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build/modamaskavo.xcarchive \
                     archive \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     SKIP_INSTALL=NO \
                     ONLY_ACTIVE_ARCH=NO \
                     -allowProvisioningUpdates \
                     2>&1 | tee build-attempt.log
          
          BUILD_RESULT=$?
          
          echo ""
          echo "📊 Resultado do build: $BUILD_RESULT"
          
          if [ $BUILD_RESULT -eq 0 ]; then
            echo "✅ Build funcionou!"
            
            # Verificar archive
            if [ -d "build/modamaskavo.xcarchive" ]; then
              echo "✅ Archive criado!"
              
              # Procurar .app
              APP_PATH=$(find build/modamaskavo.xcarchive -name "*.app" -type d | head -1)
              
              if [ -n "$APP_PATH" ]; then
                echo "📱 App encontrado: $APP_PATH"
                
                # Criar IPA
                cd build
                cp -r "$APP_PATH" ./modamaskavo.app
                mkdir -p Payload
                cp -r modamaskavo.app Payload/
                zip -r modamaskavo.ipa Payload/
                
                if [ -f "modamaskavo.ipa" ]; then
                  IPA_SIZE=$(du -sh modamaskavo.ipa | cut -f1)
                  echo "✅ IPA criado: $IPA_SIZE"
                  cp modamaskavo.ipa ../../modamaskavo-debug.ipa
                fi
              fi
            fi
          else
            echo "❌ Build falhou!"
            echo "🔍 Últimas linhas do erro:"
            tail -20 build-attempt.log
          fi
          
      - name: Relatório de diagnóstico
        script: |
          echo "📋 RELATÓRIO DE DIAGNÓSTICO"
          echo "=========================="
          
          cd ios
          
          echo "📊 Status dos arquivos:"
          echo "- Podfile: $([ -f "Podfile" ] && echo "✅" || echo "❌")"
          echo "- Podfile.lock: $([ -f "Podfile.lock" ] && echo "✅" || echo "❌")"
          echo "- Workspace: $([ -f "modamaskavo.xcworkspace/contents.xcworkspacedata" ] && echo "✅" || echo "❌")"
          echo "- Pasta Pods: $([ -d "Pods" ] && echo "✅" || echo "❌")"
          
          echo ""
          echo "📱 IPAs encontrados:"
          find .. -name "*.ipa" -exec ls -lh {} \;
          
          echo ""
          echo "📄 Logs disponíveis:"
          ls -la *.log 2>/dev/null || echo "Nenhum log encontrado"
          
    artifacts:
      - ios/pod-install.log
      - ios/pod-install-retry.log
      - ios/build-attempt.log
      - ios/Podfile.lock
      - ios/build/*.ipa
      - ios/build/*.app
      - ios/build/*.xcarchive
      - "*.ipa"
