workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1

    environment:
      groups:
        - apple_developer_portal_credentials
      vars:
        XCODE_SCHEME: 'modamaskavo'
        BUNDLE_ID: 'com.modamaskavo.app' # Substitua pelo seu bundle identifier real
      ios_signing:
        distribution_type: development # ou ad-hoc, app-store, enterprise
        bundle_identifier: $BUNDLE_ID

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Clean and Install CocoaPods
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods
          rm -f Podfile.lock
          pod install

      - name: Set up code signing settings on Xcode project
        script: |
          # Inicializa o keychain
          keychain initialize

          # Busca os arquivos de assinatura do Apple Developer Portal
          # Substitua o tipo conforme sua necessidade (IOS_APP_DEVELOPMENT, IOS_APP_ADHOC, IOS_APP_STORE)
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT

          # Adiciona os certificados ao keychain
          keychain add-certificates

          # Configura o projeto Xcode para usar os perfis
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          if [ -d "ios/modamaskavo.xcworkspace" ]; then
            echo "Usando .xcworkspace"
            xcode-project build-ipa \
              --workspace "ios/modamaskavo.xcworkspace" \
              --scheme "$XCODE_SCHEME"
          elif [ -d "ios/modamaskavo.xcodeproj" ]; then
            echo "Usando .xcodeproj"
            xcode-project build-ipa \
              --project "ios/modamaskavo.xcodeproj" \
              --scheme "$XCODE_SCHEME"
          else
            echo "Erro: Não foi encontrado .xcworkspace nem .xcodeproj na pasta ios/"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
