workflows:
  ios-workflow:
    name: iOS Build Sem Dependências
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
    scripts:
      - name: Install npm dependencies only
        script: |
          npm install --production
          
      - name: Skip CocoaPods - Use pre-built workspace
        script: |
          echo "Pulando CocoaPods, usando workspace existente..."
          cd ios
          
          # Verificar se workspace existe
          if [ -d "modamaskavo.xcworkspace" ]; then
            echo "✅ Workspace encontrado!"
          else
            echo "❌ Workspace não existe, criando minimal..."
            # Criar workspace mínimo
            mkdir -p modamaskavo.xcworkspace
            cat > modamaskavo.xcworkspace/contents.xcworkspacedata << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <Workspace version="1.0">
             <FileRef location="group:modamaskavo.xcodeproj">
             </FileRef>
          </Workspace>
          EOF
          fi
          
      - name: Build iOS app DIRETO
        script: |
          cd ios
          
          # Tentar build direto do projeto
          xcodebuild -project modamaskavo.xcodeproj \
                     -scheme modamaskavo \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build/modamaskavo.xcarchive \
                     archive \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO
          
          echo "✅ Build concluído!"
          
      - name: Create IPA manually
        script: |
          cd ios/build
          
          # Extrair .app do archive
          cp -r modamaskavo.xcarchive/Products/Applications/modamaskavo.app ./
          
          # Criar Payload
          mkdir Payload
          cp -r modamaskavo.app Payload/
          
          # Criar IPA
          zip -r modamaskavo.ipa Payload/
          
          echo "✅ IPA criado manualmente!"
          ls -la *.ipa
          
    artifacts:
      - ios/build/*.ipa
      - ios/build/*.app
      - ios/build/*.xcarchive
