# codemagic.yaml - VERSÃO COM Node.js 18.17.0 (com workarounds)
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - apple_developer_portal_credentials
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
        BUNDLE_ID: "com.modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.modamaskavo

    scripts:
      - name: Install npm dependencies
        script: |
          # Ignorar avisos de engine e usar legacy peer deps
          npm ci --legacy-peer-deps --engine-strict=false

      - name: Install Firebase dependencies (if needed)
        script: |
          # Verificar se Firebase está no package.json
          if grep -q "@react-native-firebase/app" package.json; then
            echo "Firebase encontrado no package.json, instalando..."
            npm install @react-native-firebase/app @react-native-firebase/auth @react-native-firebase/firestore --legacy-peer-deps --engine-strict=false
          else
            echo "Firebase não está no package.json, pulando instalação..."
          fi
          
          # Verificar se foi instalado
          if [ -f "node_modules/@react-native-firebase/app/scripts/RNFBCocoaPods.rb" ]; then
            echo "✅ Firebase disponível"
            ls -la node_modules/@react-native-firebase/app/scripts/
          else
            echo "⚠️ Firebase não disponível, mas continuando..."
          fi

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods
          rm -f Podfile.lock
          pod install --verbose

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          cd ios
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --clean

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
