# codemagic.yaml - ADICIONANDO RCTREQUIRED
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: HACK BRUTAL - Criar TODOS os podspecs React Native
        script: |
          # Criar ReactCommon.podspec com todos os subspecs
          cat > node_modules/react-native/ReactCommon/ReactCommon.podspec << 'EOF'
          Pod::Spec.new do |s|
            s.name                   = "ReactCommon"
            s.version                = "1000.0.0"
            s.summary                = "ReactCommon with all subspecs"
            s.homepage               = "https://reactnative.dev/"
            s.license                = "MIT"
            s.author                 = "Meta Platforms, Inc."
            s.platforms              = { :ios => "15.0" }
            s.source                 = { :path => "." }
            s.source_files           = "**/*.{h,m,mm,cpp,c}"
            s.header_dir             = "ReactCommon"
            s.public_header_files    = "**/*.h"
            
            s.subspec "turbomodule" do |ss|
              ss.source_files = "**/*.{h,m,mm,cpp,c}"
              ss.header_dir = "ReactCommon"
              
              ss.subspec "core" do |sss|
                sss.source_files = "**/*.{h,m,mm,cpp,c}"
                sss.header_dir = "ReactCommon"
                sss.public_header_files = "**/*.h"
              end
            end
            
            s.subspec "jsi" do |ss|
              ss.source_files = "**/*.{h,m,mm,cpp,c}"
              ss.header_dir = "ReactCommon"
            end
            
            s.subspec "callinvoker" do |ss|
              ss.source_files = "**/*.{h,m,mm,cpp,c}"
              ss.header_dir = "ReactCommon"
            end
            
            s.subspec "runtimeexecutor" do |ss|
              ss.source_files = "**/*.{h,m,mm,cpp,c}"
              ss.header_dir = "ReactCommon"
            end
          end
          EOF
          
          # Criar script Ruby para criar TODOS os podspecs
          cat > fix_podspecs.rb << 'EOF'
          require 'fileutils'

          def create_podspec(name, path)
            FileUtils.mkdir_p(path)
            File.write("#{path}/#{name}.podspec", <<~PODSPEC)
              Pod::Spec.new do |s|
                s.name                   = "#{name}"
                s.version                = "1000.0.0"
                s.summary                = "Auto-generated podspec for compatibility"
                s.homepage               = "https://reactnative.dev/"
                s.license                = "MIT"
                s.author                 = "Meta Platforms, Inc."
                s.platforms              = { :ios => "15.0" }
                s.source                 = { :path => "." }
                s.source_files           = "*.{h,m,mm,cpp,c}"
                s.header_dir             = "React"
                s.public_header_files    = "*.h"
              end
            PODSPEC
            FileUtils.touch("#{path}/dummy.cpp")
            puts "✅ Created #{name}.podspec"
          end

          # Lista COMPLETA de podspecs problemáticos
          podspecs = [
            ["RCTRequired", "node_modules/react-native/Libraries/Required"],
            ["React-RuntimeApple", "node_modules/react-native/ReactCommon/react/runtime/platform/ios"],
            ["React-RuntimeCore", "node_modules/react-native/ReactCommon/react/runtime"],
            ["React-logger", "node_modules/react-native/ReactCommon/logger"],
            ["React-oscompat", "node_modules/react-native/ReactCommon/oscompat"],
            ["React-NativeModulesApple", "node_modules/react-native/ReactCommon/react/nativemodule/core/platform/ios"],
            ["React-RCTNetwork", "node_modules/react-native/Libraries/Network"],
            ["FBLazyVector", "node_modules/react-native/Libraries/FBLazyVector"],
            ["React-Core", "node_modules/react-native/React"],
            ["React-CoreModules", "node_modules/react-native/React/CoreModules"],
            ["React-RCTAppDelegate", "node_modules/react-native/Libraries/AppDelegate"],
            ["React-RCTImage", "node_modules/react-native/Libraries/Image"],
            ["React-RCTText", "node_modules/react-native/Libraries/Text"],
            ["React-RCTVibration", "node_modules/react-native/Libraries/Vibration"],
            ["React-RCTLinking", "node_modules/react-native/Libraries/LinkingIOS"],
            ["React-RCTSettings", "node_modules/react-native/Libraries/Settings"],
            ["React-RCTBlob", "node_modules/react-native/Libraries/Blob"],
            ["React-RCTAnimation", "node_modules/react-native/Libraries/NativeAnimation"],
            ["React-jsi", "node_modules/react-native/ReactCommon/jsi"],
            ["React-jsiexecutor", "node_modules/react-native/ReactCommon/jsiexecutor"],
            ["React-jsinspector", "node_modules/react-native/ReactCommon/jsinspector"],
            ["React-callinvoker", "node_modules/react-native/ReactCommon/callinvoker"],
            ["React-runtimeexecutor", "node_modules/react-native/ReactCommon/runtimeexecutor"],
            ["React-perflogger", "node_modules/react-native/ReactCommon/reactperflogger"],
            ["React-cxxreact", "node_modules/react-native/ReactCommon/cxxreact"],
            ["React-hermes", "node_modules/react-native/ReactCommon/hermes"],
            ["React-utils", "node_modules/react-native/ReactCommon/react/utils"],
            ["React-debug", "node_modules/react-native/ReactCommon/react/debug"],
            ["React-Mapbuffer", "node_modules/react-native/ReactCommon/react/renderer/mapbuffer"],
            ["Yoga", "node_modules/react-native/ReactCommon/yoga"],
            ["RCTTypeSafety", "node_modules/react-native/Libraries/TypeSafety"],
            ["React-RCTActionSheet", "node_modules/react-native/Libraries/ActionSheetIOS"],
            ["React-RCTAlert", "node_modules/react-native/Libraries/Alert"],
            ["React-RCTPushNotification", "node_modules/react-native/Libraries/PushNotificationIOS"]
          ]

          podspecs.each do |name, path|
            create_podspec(name, path)
          end

          puts "✅ Todos os podspecs criados incluindo RCTRequired!"
          EOF
          
          # Executar o script Ruby
          ruby fix_podspecs.rb
          
      - name: Create Podfile with iOS 15.0
        script: |
          cat > ios/Podfile << 'EOF'
          require_relative '../node_modules/react-native/scripts/react_native_pods'
          
          platform :ios, '15.0'
          
          target 'modamaskavo' do
            config = use_native_modules!
            
            use_react_native!(
              :path => config[:reactNativePath],
              :hermes_enabled => false,
              :fabric_enabled => false,
              :new_arch_enabled => false
            )
            
            post_install do |installer|
              react_native_post_install(installer)
              
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
                  config.build_settings['RCT_NEW_ARCH_ENABLED'] = 'NO'
                end
              end
            end
          end
          EOF
      - name: Clean everything
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          rm -rf build
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
