# codemagic.yaml - CRIANDO TODOS OS PODSPECS VAZIOS
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "modamaskavo.xcworkspace"
        XCODE_SCHEME: "modamaskavo"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Create ALL React Native podspecs with iOS 12.0
        script: |
          # Template para podspec vazio
          create_podspec() {
            local name=$1
            local path=$2
            mkdir -p "$path"
            cat > "$path/${name}.podspec" << EOF
          Pod::Spec.new do |s|
            s.name                   = "$name"
            s.version                = "1000.0.0"
            s.summary                = "Empty podspec for compatibility"
            s.homepage               = "https://reactnative.dev/"
            s.license                = "MIT"
            s.author                 = "Meta Platforms, Inc."
            s.platforms              = { :ios => "12.0" }
            s.source                 = { :path => "." }
            s.source_files           = "*.{h,m,mm,cpp,c}"
            s.header_dir             = "React"
          end
          EOF
            touch "$path/dummy.cpp"
          }
          
          # Criar todos os podspecs problemáticos
          create_podspec "React-logger" "node_modules/react-native/ReactCommon/logger"
          create_podspec "React-oscompat" "node_modules/react-native/ReactCommon/oscompat"
          create_podspec "React-RuntimeApple" "node_modules/react-native/ReactCommon/react/runtime/platform/ios"
          create_podspec "React-RuntimeCore" "node_modules/react-native/ReactCommon/react/runtime"
          create_podspec "ReactCommon" "node_modules/react-native/ReactCommon"
          
          echo "✅ Todos os podspecs criados!"
          
      - name: Create Podfile with iOS 12.0
        script: |
          cat > ios/Podfile << 'EOF'
          require_relative '../node_modules/react-native/scripts/react_native_pods'
          
          platform :ios, '12.0'
          
          target 'modamaskavo' do
            config = use_native_modules!
            
            use_react_native!(
              :path => config[:reactNativePath],
              :hermes_enabled => false,
              :fabric_enabled => false,
              :new_arch_enabled => false
            )
            
            post_install do |installer|
              react_native_post_install(installer)
              
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                  config.build_settings['RCT_NEW_ARCH_ENABLED'] = 'NO'
                end
              end
            end
          end
          EOF
      - name: Clean everything
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          rm -rf build
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath build-output/app.xcarchive \
                     archive | xcpretty
    artifacts:
      - ios/build-output/app.xcarchive
