//User
export const FETCH_ADDRESS_REQUEST = 'FETCH_ADDRESS_REQUEST';
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';
export const FETCH_ADDRESS_FAILURE = 'FETCH_ADDRESS_FAILURE';
export const MODIFY_ADDRESS = 'MODIFY_ADDRESS';
export const MODIFY_NEIGHBORHOOD = 'MODIFY_NEIGHBORHOOD';
export const MODIFY_CITY = 'MODIFY_CITY';
export const MODIFY_STATE = 'MODIFY_STATE';
export const REGISTRATION_IN_PROGRESS = 'REGISTRATION_IN_PROGRESS';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const MODIFY_NAME = 'MODIFY_NAME';
export const MODIFY_EMAIL = 'MODIFY_EMAIL';
export const MODIFY_PASSWORD = 'MODIFY_PASSWORD';
export const MODIFY_CPFCNPJ = 'MODIFY_CPFCNPJ';
export const MODIFY_PHONE = 'MODIFY_PHONE';
export const MODIFY_CEP = 'MODIFY_CEP';
export const MODIFY_NUMBER = 'MODIFY_NUMBER';
export const MODIFY_COMPLEMENT = 'MODIFY_COMPLEMENT';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SAVE_PROFILE_IN_PROGRESS = 'SAVE_PROFILE_IN_PROGRESS';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_ERROR = 'SAVE_PROFILE_ERROR';
export const DATA_USER = 'DATA_USER';
export const DATA_USERS_FULL = 'DATA_USERS_FULL';
export const MODIFY_PHOTO = 'MODIFY_PHOTO';
export const SIGN_OUT = 'SIGN_OUT';
export const LOGIN_GOOGLE_IN_PROGRESS = 'LOGIN_GOOGLE_IN_PROGRESS';
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS';
export const LOGIN_GOOGLE_ERROR = 'LOGIN_GOOGLE_ERROR';
export const FORGOT_PASSWORD_IN_PROGRESS = 'FORGOT_PASSWORD_IN_PROGRESS';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

//Order
export const ORDER_REGISTRATION_IN_PROGRESS = 'ORDER_REGISTRATION_IN_PROGRESS';
export const ORDER_REGISTRATION_SUCCESS = 'ORDER_REGISTRATION_SUCESS';
export const ORDER_REGISTRATION_ERROR = 'ORDER_REGISTRATION_ERROR';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_ERROR = 'CANCEL_ORDER_ERROR';
export const SET_PRICE_ORDER = 'SET_PRICE_ORDER';
export const SET_PRICE_ORDER_ERROR = 'SET_PRICE_ORDER_ERROR';
export const SET_ESTIMATED_FINISH_ORDER = 'SET_ESTIMATED_FINISH_ORDER';
export const SET_ESTIMATED_FINISH_ORDER_ERROR =
  'SET_ESTIMATED_FINISH_ORDER_ERROR';
export const SET_CODE_TRACK_ORDER = 'SET_CODE_TRACK_ORDER';
export const SET_CODE_TRACK_ORDER_ERROR = 'SET_CODE_TRACK_ORDER_ERROR';
export const PAYMENT_SUCCESS_ORDER = 'PAYMENT_SUCCESS_ORDER';
export const PAYMENT_SUCCESS_ORDER_ERROR = 'PAYMENT_SUCCESS_ORDER_ERROR';
export const DATA_ORDERS = 'DATA_ORDERS';
export const DATA_ORDERS_FULL = 'DATA_ORDERS_FULL';
export const MODIFY_TYPE = 'MODIFY_TYPE';
export const MODIFY_SEGMENT = 'MODIFY_SEGMENT';
export const MODIFY_AMOUNT_PIECES = 'MODIFY_AMOUNT_PIECES';
export const MODIFY_TAM = 'MODIFY_TAM';
export const MODIFY_DESCRIPTION = 'MODIFY_DESCRIPTION';

//Config
export const SAVE_CONFIG_IN_PROGRESS = 'SAVE_CONFIG_IN_PROGRESS';
export const SAVE_CONFIG_SUCCESS = 'SAVE_CONFIG_SUCCESS';
export const SAVE_CONFIG_ERROR = 'SAVE_CONFIG_ERROR';
export const DATA_CONFIG = 'DATA_CONFIG';
export const MODIFY_PHONE_CONFIG = 'MODIFY_PHONE_CONFIG';
export const MODIFY_ENVIRONMENT = 'MODIFY_ENVIRONMENT';
export const MODIFY_KEY_API_SANDBOX = 'MODIFY_KEY_API_SANDBOX';
export const MODIFY_KEY_API_PROD = 'MODIFY_KEY_API_PROD';

//Product
// actionTypes.js (adicione estes tipos aos seus action types existentes)

// Produtos
export const FETCH_PRODUCTS_IN_PROGRESS = 'FETCH_PRODUCTS_IN_PROGRESS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const LOAD_MORE_PRODUCTS = 'LOAD_MORE_PRODUCTS';

// Variações
export const FETCH_VARIATIONS_IN_PROGRESS = 'FETCH_VARIATIONS_IN_PROGRESS';
export const FETCH_VARIATIONS_SUCCESS = 'FETCH_VARIATIONS_SUCCESS';
export const FETCH_VARIATIONS_ERROR = 'FETCH_VARIATIONS_ERROR';

// Estoque
export const UPDATE_PRODUCT_STOCK_IN_PROGRESS =
  'UPDATE_PRODUCT_STOCK_IN_PROGRESS';
export const UPDATE_PRODUCT_STOCK_SUCCESS = 'UPDATE_PRODUCT_STOCK_SUCCESS';
export const UPDATE_PRODUCT_STOCK_ERROR = 'UPDATE_PRODUCT_STOCK_ERROR';

// Variações selecionadas
export const SELECT_VARIATION = 'SELECT_VARIATION';

// Carrossel de imagens
export const SET_ACTIVE_IMAGE_INDEX = 'SET_ACTIVE_IMAGE_INDEX';

// Dropdowns
export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';
export const SET_DROPDOWN_LAYOUT = 'SET_DROPDOWN_LAYOUT';
