default_platform(:ios)

platform :ios do
  desc "Build e assina o app para distribuição"
  lane :build_and_sign do
    build_app(
      scheme: "modamaskavo",
      export_method: "app-store",
      output_directory: "./",
      output_name: "modamaskavo.ipa",
      export_team_id: "4XW8DF3J82"
    )
  end
end
