default_platform(:ios)

platform :ios do
  desc "Build e assina o app para distribuição"
  lane :build_and_sign do
    build_app(
      scheme: "modamaskavo",
      export_method: "app-store",
      configuration: "Release",
      export_team_id: "4XW8DF3J82",
      xcargs: "-allowProvisioningUpdates"
    )
  end
end
