name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Permite executar manualmente

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        cd ios && pod install
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    
    - name: Install Provisioning Profile
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: com.modamaskavo # Substitua pelo seu bundle ID
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    
    - name: Build iOS Archive
      run: |
        cd ios
        xcodebuild -workspace modamaskavo.xcworkspace \
                   -scheme modamaskavo \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -archivePath $PWD/build/modamaskavo.xcarchive \
                   archive
    
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
                   -archivePath $PWD/build/modamaskavo.xcarchive \
                   -exportOptionsPlist exportOptions.plist \
                   -exportPath $PWD/build
    
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: modamaskavo-ios
        path: ios/build/*.ipa
        retention-days: 30
    
    - name: Upload to TestFlight (opcional)
      if: github.ref == 'refs/heads/main'
      run: |
        cd ios
        xcrun altool --upload-app \
                     --type ios \
                     --file build/*.ipa \
                     --username ${{ secrets.APPLE_ID }} \
                     --password ${{ secrets.APPLE_PASSWORD }}
