name: Build iOS with RN CLI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
  
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
    
    - name: Install iOS dependencies
      run: |
        cd ios
        rm -rf Pods Podfile.lock
        pod install --repo-update
    
    - name: Build with React Native CLI
      run: |
        npx react-native build-ios --mode Debug
    
    - name: Create API Key file
      run: |
        mkdir -p ~/.appstoreconnect/private_keys
        echo "${{ secrets.APPSTORE_PRIVATE_KEY }}" | base64 -d > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8
    
    - name: Build with automatic signing
      run: |
        cd ios
        xcodebuild -workspace modamaskavo.xcworkspace \
                   -scheme modamaskavo \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -allowProvisioningUpdates \
                   -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8 \
                   -authenticationKeyID ${{ secrets.APPSTORE_KEY_ID }} \
                   -authenticationKeyIssuerID ${{ secrets.APPSTORE_ISSUER_ID }} \
                   -archivePath $PWD/build/modamaskavo.xcarchive \
                   archive
    
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
                   -archivePath $PWD/build/modamaskavo.xcarchive \
                   -exportOptionsPlist exportOptions.plist \
                   -exportPath $PWD/build \
                   -allowProvisioningUpdates \
                   -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8 \
                   -authenticationKeyID ${{ secrets.APPSTORE_KEY_ID }} \
                   -authenticationKeyIssuerID ${{ secrets.APPSTORE_ISSUER_ID }}
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: modamaskavo-ios
        path: ios/build/*.ipa
