name: Build iOS Automático (Simplificado)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Configurar Chave App Store Connect
      run: |
        mkdir -p ~/.appstoreconnect
        echo "${{ secrets.APPSTORE_PRIVATE_KEY }}" > ~/.appstoreconnect/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8
        chmod 600 ~/.appstoreconnect/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8

    - name: Instalar Dependências Node e Pods
      run: |
        npm install
        sudo gem install cocoapods -v 1.13.0 # ou a versão que quiser
        pod install --repo-update

    - name: Instalar Fastlane globalmente
      run: sudo gem install fastlane

    - name: Construir e Assinar o App com Fastlane
      run: |
        cd ios
        fastlane build_and_sign

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: modamaskavo-ipa
        path: ios/*.ipa
      if: success()
