name: Build iOS Automático

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
  
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
    
    - name: Install dependencies
      run: |
        npm install
        cd ios
        pod install --repo-update
        
    - name: Configure App Store Connect API
      run: |
        mkdir -p ~/.appstoreconnect/private_keys
        # O comando abaixo foi corrigido para não decodificar a chave, pois ela já está em texto
        echo "${{ secrets.APPSTORE_PRIVATE_KEY }}" > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8
        chmod 600 ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8
    
    - name: Build and Export IPA
      run: |
        cd ios
        rm -rf build
        
        # Este comando foi ajustado para usar a identidade de assinatura de App Store
        # Isso permite que o build funcione sem um certificado de desenvolvimento, usando apenas os de distribuição.
        xcodebuild archive \
          -workspace modamaskavo.xcworkspace \
          -scheme modamaskavo \
          -configuration Release \
          -archivePath ./build/modamaskavo.xcarchive \
          -allowProvisioningUpdates \
          CODE_SIGN_STYLE="Manual" \
          DEVELOPMENT_TEAM="4XW8DF3J82" \
          PROVISIONING_PROFILE_SPECIFIER="Distribuição" \
          CODE_SIGN_IDENTITY="Apple Distribution: Alisson Schmitz de Medeiros (4XW8DF3J82)" \
          GCC_WARN_INHIBIT_ALL_WARNINGS=YES \
          -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8 \
          -authenticationKeyID ${{ secrets.APPSTORE_KEY_ID }} \
          -authenticationKeyIssuerID ${{ secrets.APPSTORE_ISSUER_ID }}
        
        # O comando 'exportArchive' usa as mesmas credenciais para finalizar o IPA
        /usr/bin/xcrun xcodebuild -exportArchive \
          -archivePath ./build/modamaskavo.xcarchive \
          -exportPath ./build \
          -exportOptionsPlist ./exportOptions.plist \
          -allowProvisioningUpdates \
          -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8 \
          -authenticationKeyID ${{ secrets.APPSTORE_KEY_ID }} \
          -authenticationKeyIssuerID ${{ secrets.APPSTORE_ISSUER_ID }}
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: modamaskavo-ipa
        path: ios/build/*.ipa
      if: success()
